#!/usr/bin/env python3
"""Generates skrifa/oracle_tests/cases_wbtest.mbt from the oracle.

Run from the worktree root after `sh target/scratch/listfonts.sh`.
Full oracle outputs are written to target/scratch/expected/<name>.txt.
"""
import os, subprocess, sys, glob

ORACLE = 'target/scratch/oracle/target/release/skrifa-oracle'
OUT_DIR = 'target/scratch/expected'
os.makedirs(OUT_DIR, exist_ok=True)


def fnv(data: bytes) -> int:
    h = 0xcbf29ce484222325
    for b in data:
        h ^= b
        h = (h * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF
    return h


cases = []  # (name, kind, root, path, stream_len, stream_fnv)

for f in sorted(glob.glob('target/assets/fonts/Foxit*.pfb')):
    base = os.path.basename(f)
    cases.append((base + '.cff', 'cff', 'assets', 'fonts/' + base, -1, 0, f))
for f in ['DejaVuSansMono.ttf', 'DejaVuSansMono-Bold.ttf', 'LibertinusSerif-Regular.otf', 'NewCM10-Regular.otf']:
    cases.append((f + '.otf', 'otf', 'assets', 'fonts/' + f, -1, 0, 'target/assets/fonts/' + f))

pdfs = sorted(glob.glob('target/hayro/hayro-tests/pdfs/custom/font_*.pdf')) + \
    ['target/hayro/hayro-tests/pdfs/custom/fonts_type1_latex.pdf', 'target/devassets/images/diagrams.pdf']
for pdf in pdfs:
    b = os.path.basename(pdf)[:-4]
    if pdf.startswith('target/hayro/'):
        root, rel = 'hayro', pdf[len('target/hayro/'):]
    else:
        root, rel = 'devassets', pdf[len('target/devassets/'):]
    d = os.path.join('target/scratch/fonts', b)
    if not os.path.isdir(d):
        continue
    for fn in sorted(os.listdir(d), key=lambda s: int(s.split('.')[0])):
        i, key = fn.split('.')
        data = open(os.path.join(d, fn), 'rb').read()
        kinds = {'FontFile': ['t1', 'cff'], 'FontFile2': ['otf'], 'FontFile3': ['cff', 'otf']}[key]
        for kind in kinds:
            cases.append((f'{b}.{i}.{kind}', kind, root, rel, len(data), fnv(data), os.path.join(d, fn)))

only = sys.argv[1:] if len(sys.argv) > 1 else None
rows = []
for (name, kind, root, rel, slen, sfnv, local) in cases:
    out_path = os.path.join(OUT_DIR, name + '.txt')
    if only is None or name in only or os.path.exists(out_path) is False:
        res = subprocess.run([ORACLE, kind, local], capture_output=True)
        if res.returncode != 0:
            print('oracle failed', name, res.stderr.decode()[:300], file=sys.stderr)
            continue
        open(out_path, 'wb').write(res.stdout)
    out = open(out_path, 'rb').read()
    rows.append((name, kind, root, rel, slen, sfnv, len(out), fnv(out)))

with open('skrifa/oracle_tests/cases_wbtest.mbt', 'w') as f:
    f.write('// Generated by scratch gen_cases.py from the skrifa oracle. Do not edit.\n\n')
    f.write('///|\n')
    f.write('/// (name, kind, root, path, stream_len, stream_fnv, out_len, out_fnv)\n')
    f.write('let cases : Array[(String, String, String, String, Int, UInt64, Int, UInt64)] = [\n')
    for (name, kind, root, rel, slen, sfnv, olen, ofnv) in rows:
        f.write(f'  ("{name}", "{kind}", "{root}", "{rel}", {slen}, 0x{sfnv:016x}UL, {olen}, 0x{ofnv:016x}UL),\n')
    f.write(']\n')
print(len(rows), 'cases')
