#!/usr/bin/env python3
"""Generate `moxcms/pxfm/tables_gen.mbt` from the `pxfm` 0.1.30 sources.

Only the tables used by `f_pow` / `f_powf` are extracted. Tuple tables are
flattened in declaration order (e.g. `(lo, hi)` pairs become `lo, hi, ...`).

Usage: python3 moxcms/pxfm/gen_tables.py [path/to/pxfm-0.1.30/src]
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

TABLES = [
    # (file, rust name, moonbit name, type, upstream shape comment)
    ("pow_tables.rs", "POW_INVERSE", "pow_inverse", "UInt64", "[u64; 182]"),
    ("pow_tables.rs", "POW_LOG_INV", "pow_log_inv", "UInt64", "[(u64, u64); 182]"),
    ("pow_tables.rs", "EXP2_MID1", "exp2_mid1", "UInt64", "[(u64, u64); 64]"),
    ("powf_tables.rs", "POWF_R2", "powf_r2", "UInt64", "[u64; 193]"),
    ("powf_tables.rs", "LOG2_R_TD", "log2_r_td", "UInt64", "[(u64, u64, u64); 128]"),
    ("powf_tables.rs", "LOG2_R2_DD", "log2_r2_dd", "UInt64", "[(u64, u64); 193]"),
    ("exponents/exp.rs", "EXP_REDUCE_T0", "exp_reduce_t0", "UInt64", "[(u64, u64); 64]"),
    ("exponents/exp.rs", "EXP_REDUCE_T1", "exp_reduce_t1", "UInt64", "[(u64, u64); 64]"),
    ("logs/logf.rs", "LOG_REDUCTION_F32", "log_reduction_f32", "UInt", "[u32; 128]"),
    ("logs/log2f.rs", "LOG2_R", "log2_r", "UInt64", "[u64; 128]"),
    (
        "logs/log2.rs",
        "LOG_RANGE_REDUCTION",
        "log_range_reduction_table",
        "UInt64",
        "[u64; 128]",
    ),
]


def extract(src, name):
    m = re.search(r"static\s+" + name + r"\s*:[^=]*=\s*", src)
    if not m:
        sys.exit(f"table {name} not found")
    start = m.end()
    # The table ends at the first `];` after the start.
    end = re.compile(r"\]\s*\)?\s*;").search(src, start).start()
    body = src[start:end]
    body = re.sub(r"//[^\n]*", "", body)
    return [int(v.replace("_", ""), 16) for v in re.findall(r"0x[0-9a-fA-F_]+", body)]


SIGNED_TABLES = [
    ("logs/log_range_reduction.rs", "S2", "log_s2", 193),
    ("logs/log_range_reduction.rs", "S3", "log_s3", 161),
    ("logs/log_range_reduction.rs", "S4", "log_s4", 130),
]

DYADIC_TABLES = [
    ("logs/log_dyadic.rs", "LOG_STEP_1", "log_step_1", 128),
    ("logs/log_dyadic.rs", "LOG_STEP_2", "log_step_2", 193),
    ("logs/log_dyadic.rs", "LOG_STEP_3", "log_step_3", 161),
    ("logs/log_dyadic.rs", "LOG_STEP_4", "log_step_4", 130),
    ("pow_tables.rs", "EXP_T1_2_DYADIC", "exp_t1_2_dyadic", 64),
    ("pow_tables.rs", "EXP_T2_2_DYADIC", "exp_t2_2_dyadic", 64),
]


def extract_dyadic(src, name):
    m = re.search(r"static\s+" + name + r"\s*:[^=]*=", src)
    if not m:
        sys.exit(f"table {name} not found")
    start = m.end()
    end = re.compile(r"\]\s*;").search(src, start).start()
    body = re.sub(r"//[^\n]*", "", src[start:end])
    out = []
    for sign, exp, mant in re.findall(
        r"sign:\s*DyadicSign::(Pos|Neg),\s*exponent:\s*(-?\d+),\s*mantissa:\s*(0x[0-9a-fA-F_]+|0)_?u128",
        body,
    ):
        v = int(mant.replace("_", ""), 16) if mant.startswith("0x") else 0
        out.append((sign == "Neg", int(exp), v >> 64, v & ((1 << 64) - 1)))
    return out


def main():
    src_dir = (
        sys.argv[1]
        if len(sys.argv) > 1
        else os.path.join(ROOT, "target", "reg", "pxfm-0.1.30", "src")
    )
    out = [
        "// Generated by moxcms/pxfm/gen_tables.py from pxfm 0.1.30. Do not edit.",
        "",
    ]
    for file, name, mbt, ty, shape in TABLES:
        src = open(os.path.join(src_dir, file)).read()
        values = extract(src, name)
        suffix = "UL" if ty == "UInt64" else "U"
        width = 3 if ty == "UInt64" else 6
        out.append("///|")
        out.append(f"/// `{name}: {shape}` ({file}), flattened.")
        out.append(f"let {mbt} : FixedArray[{ty}] = [")
        for i in range(0, len(values), width):
            out.append(
                "  " + ", ".join(f"0x{v:x}{suffix}" for v in values[i : i + width]) + ","
            )
        out.append("]")
        out.append("")
    for file, name, mbt, n in SIGNED_TABLES:
        src = open(os.path.join(src_dir, file)).read()
        m = re.search(r"static\s+" + name + r"\s*:[^=]*=\s*", src)
        end = re.compile(r"\]\s*;").search(src, m.end()).start()
        body = re.sub(r"//[^\n]*", "", src[m.end() : end])
        values = [int(v, 16) for v in re.findall(r"-?0x[0-9a-fA-F]+", body)]
        if len(values) != n:
            sys.exit(f"{name}: expected {n} entries, got {len(values)}")
        out.append("///|")
        out.append(f"/// `{name}: [i32; {n}]` ({file}).")
        out.append(f"let {mbt} : FixedArray[Int] = [")
        for i in range(0, len(values), 12):
            out.append("  " + ", ".join(str(v) for v in values[i : i + 12]) + ",")
        out.append("]")
        out.append("")
    for file, name, mbt, n in DYADIC_TABLES:
        src = open(os.path.join(src_dir, file)).read()
        values = extract_dyadic(src, name)
        if len(values) != n:
            sys.exit(f"{name}: expected {n} entries, got {len(values)}")
        out.append("///|")
        out.append(f"/// `{name}: [DyadicFloat128; {n}]` ({file}).")
        out.append(f"let {mbt} : FixedArray[DyadicFloat128] = [")
        for neg, exp, hi, lo in values:
            out.append(f"  dyadic({str(neg).lower()}, {exp}, 0x{hi:x}UL, 0x{lo:x}UL),")
        out.append("]")
        out.append("")
    with open(os.path.join(HERE, "tables_gen.mbt"), "w") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main()
