// cmarker 0.1.10: an HTML description list with the package's default `<dl>` handler, which
// passes (term, description) arrays to `terms`: a type error inside a closure of the package
// that is called from markup generated by the plugin and evaluated with `eval`.
// Engine: error trace through eval'd source into package closures.
#import "@preview/cmarker:0.1.10"

#set page(width: 100mm, height: 60mm, margin: 10mm)

#cmarker.render(```md
# Knots

<dl>
  <dt>Bowline</dt>
  <dd>A fixed loop that does not slip.</dd>
  <dt>Clove hitch</dt>
  <dd>A quick hitch around a post.</dd>
</dl>
```)
