# PowerShell equivalent of `gen-fonts` (moon runs it on Windows): generates
# fonts_gen.c and fonts_wasm_gen.mbt from the font files.
#
# Usage: gen-fonts.ps1 [--prefix=<name>] <fonts_gen.c> <fonts_wasm_gen.mbt> <font files...>
# (`--prefix` names the C symbols, see gen-fonts)
$ErrorActionPreference = "Stop"
$prefix = "typst_font"
$rest = @($args)
if ($rest.Length -gt 0 -and "$($rest[0])".StartsWith("--prefix=")) {
  $prefix = "$($rest[0])".Substring(9)
  $rest = @($rest[1..($rest.Length - 1)])
}
$outC = $rest[0]
$outMbt = $rest[1]
# The generator scripts are inputs of the pre-build step too.
$fonts = @($rest[2..($rest.Length - 1)] | Where-Object { $_ -match '\.(otf|ttf|otc|ttc)$' })
if ($fonts.Length -eq 0) { throw "gen-fonts: no font files" }
# The directory of the font files (relative to the module root).
$from = ((Split-Path -Parent $fonts[0]) -replace '\\', '/') -replace '^\./', ''
$header = "Generated by typst_assets/fonts/gen-fonts from $from. Do not edit."
$chunkLines = 8000
$chunkBytes = 64

$c = New-Object System.Text.StringBuilder
$m = New-Object System.Text.StringBuilder
[void]$c.Append("// $header`n`n#include <stdint.h>`n#include <stddef.h>`n`n")
# The rows are initialized without their terminating NUL on purpose.
[void]$c.Append("#if defined(__clang__)`n#pragma clang diagnostic ignored `"-Wunknown-warning-option`"`n#pragma clang diagnostic ignored `"-Wunterminated-string-initialization`"`n#elif defined(__GNUC__)`n#pragma GCC diagnostic ignored `"-Wpragmas`"`n#pragma GCC diagnostic ignored `"-Wunterminated-string-initialization`"`n#elif defined(_MSC_VER)`n#pragma warning(disable : 4295)`n#endif`n`n")
[void]$m.Append("// $header`n`n")
$lens = @()
$names = @()
for ($i = 0; $i -lt $fonts.Length; $i++) {
  $bytes = [System.IO.File]::ReadAllBytes((Resolve-Path $fonts[$i]))
  $lens += $bytes.Length
  $b64 = [System.Convert]::ToBase64String($bytes)
  $lines = @()
  for ($k = 0; $k -lt $b64.Length; $k += 100) {
    $lines += $b64.Substring($k, [Math]::Min(100, $b64.Length - $k))
  }
  # C: chunks of $chunkBytes raw bytes as hex escapes (see gen-fonts).
  [void]$c.Append("static const char ${prefix}_$i[][$chunkBytes] = {`n")
  for ($k = 0; $k -lt $bytes.Length; $k += $chunkBytes) {
    $n = [Math]::Min($chunkBytes, $bytes.Length - $k)
    $hex = '\x' + [System.BitConverter]::ToString($bytes, $k, $n).Replace('-', '\x')
    [void]$c.Append("  `"").Append($hex).Append("`",`n")
  }
  [void]$c.Append("};`n`n")
  $fontNames = @()
  for ($k = 0; $k -lt $lines.Length; $k++) {
    if ($k % $chunkLines -eq 0) {
      $name = "font_${i}_base64_$([int][Math]::Floor($k / $chunkLines))"
      if ($k -gt 0) { [void]$m.Append("`n") }
      [void]$m.Append("///|`nlet $name : String =`n")
      $fontNames += $name
    }
    [void]$m.Append("  #|$($lines[$k])`n")
  }
  [void]$m.Append("`n")
  $names += ($fontNames -join ", ")
}
[void]$c.Append("const char *const ${prefix}_data[] = {`n")
for ($i = 0; $i -lt $fonts.Length; $i++) { [void]$c.Append("  ${prefix}_$i[0],`n") }
[void]$c.Append("};`n`nconst int32_t ${prefix}_lens[] = {`n")
foreach ($len in $lens) { [void]$c.Append("  $len,`n") }
[void]$c.Append("};`n`nconst int32_t ${prefix}_count = $($fonts.Length);`n")
[void]$m.Append("///|`n/// The base64 data (in chunks) and decoded length of each font.`n")
[void]$m.Append("let fonts_base64 : Array[(Array[String], Int)] = [`n")
for ($i = 0; $i -lt $fonts.Length; $i++) {
  [void]$m.Append("  ([$($names[$i])], $($lens[$i])),`n")
}
[void]$m.Append("]`n")
[System.IO.File]::WriteAllText($outC, $c.ToString())
[System.IO.File]::WriteAllText($outMbt, $m.ToString())
