# PowerShell equivalent of `gen-fonts` (moon runs it on Windows): generates
# fonts_gen.c and fonts_wasm_gen.mbt from the font files.
#
# Usage: gen-fonts.ps1 <fonts_gen.c> <fonts_wasm_gen.mbt> <font files...>
$ErrorActionPreference = "Stop"
$outC = $args[0]
$outMbt = $args[1]
$fonts = $args[2..($args.Length - 1)]
$header = "Generated by typst_assets/fonts/gen-fonts from typst_assets/fonts/files. Do not edit."
$chunkLines = 8000

$c = New-Object System.Text.StringBuilder
$m = New-Object System.Text.StringBuilder
[void]$c.Append("// $header`n`n#include <stdint.h>`n#include <stddef.h>`n`n")
[void]$m.Append("// $header`n`n")
$lens = @()
$names = @()
for ($i = 0; $i -lt $fonts.Length; $i++) {
  $bytes = [System.IO.File]::ReadAllBytes((Resolve-Path $fonts[$i]))
  $lens += $bytes.Length
  $b64 = [System.Convert]::ToBase64String($bytes)
  $lines = @()
  for ($k = 0; $k -lt $b64.Length; $k += 100) {
    $lines += $b64.Substring($k, [Math]::Min(100, $b64.Length - $k))
  }
  [void]$c.Append("const char *const typst_font_$i[] = {`n")
  foreach ($line in $lines) { [void]$c.Append("  `"$line`",`n") }
  [void]$c.Append("  NULL,`n};`n`n")
  $fontNames = @()
  for ($k = 0; $k -lt $lines.Length; $k++) {
    if ($k % $chunkLines -eq 0) {
      $name = "font_${i}_base64_$([int][Math]::Floor($k / $chunkLines))"
      if ($k -gt 0) { [void]$m.Append("`n") }
      [void]$m.Append("///|`nlet $name : String =`n")
      $fontNames += $name
    }
    [void]$m.Append("  #|$($lines[$k])`n")
  }
  [void]$m.Append("`n")
  $names += ($fontNames -join ", ")
}
[void]$c.Append("const char *const *const typst_fonts[] = {`n")
for ($i = 0; $i -lt $fonts.Length; $i++) { [void]$c.Append("  typst_font_$i,`n") }
[void]$c.Append("};`n`nconst int32_t typst_font_lens[] = {`n")
foreach ($len in $lens) { [void]$c.Append("  $len,`n") }
[void]$c.Append("};`n`nconst int32_t typst_font_count = $($fonts.Length);`n")
[void]$m.Append("///|`n/// The base64 data (in chunks) and decoded length of each font.`n")
[void]$m.Append("let fonts_base64 : Array[(Array[String], Int)] = [`n")
for ($i = 0; $i -lt $fonts.Length; $i++) {
  [void]$m.Append("  ([$($names[$i])], $($lens[$i])),`n")
}
[void]$m.Append("]`n")
[System.IO.File]::WriteAllText($outC, $c.ToString())
[System.IO.File]::WriteAllText($outMbt, $m.ToString())
