#!/usr/bin/env python3
"""Extracts the examples of upstream's documentation as cases for the EDSL
conversion (docs/edsl-convert.md, section 10): the `example` raw blocks of
`.repos/typst/docs/**/*.typ` and of the Rust doc comments under
`.repos/typst/crates`, processed like `docs/src/example.rs` (`<<< ` lines
dropped, `>>>` prefixes stripped), each as a standalone document with the
page setup of the documentation's example world.

Writes one file in the suite's format per source file to
`tests/edsl_gen/docs/{typ,rs}/` (not committed); the runner's
`edsl-convert`/`edsl-suite` pick them up as the directories `docs/typ` and
`docs/rs`, and resolve the files an example names in typst-dev-assets by
file name, as the example world does.

Usage: python3 scripts/edsl_docs_examples.py
"""

import os
import re
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, ".repos", "typst", "docs")
CRATES = os.path.join(ROOT, ".repos", "typst", "crates")
OUT = os.path.join(ROOT, "tests", "edsl_gen", "docs")

FENCE = re.compile(r"^(\s*)(`{3,})(example|preview)\s*$")


def blocks(lines):
    """Yields (first line number, text lines) of the fenced example blocks."""
    i = 0
    while i < len(lines):
        m = FENCE.match(lines[i])
        if not m:
            i += 1
            continue
        fence = m.group(2)
        body = []
        j = i + 1
        while j < len(lines) and lines[j].strip() != fence:
            body.append(lines[j])
            j += 1
        closing = lines[j] if j < len(lines) else ""
        indent = min([len(l) - len(l.lstrip(" ")) for l in body + [closing]
                      if l.strip()] or [0])
        yield i + 1, [l[indent:] for l in body]
        i = j + 1


def source(body):
    out = []
    for line in body:
        if line.startswith("<<< "):
            continue
        if line.startswith(">>>"):
            line = line[3:]
        # A line that looks like a test header would end the case.
        if line.startswith("---"):
            return None
        out.append(line)
    return ("#set page(width: 240pt, height: auto, margin: 15pt)\n"
            + "\n".join(out) + "\n")


def main():
    if os.path.exists(OUT):
        shutil.rmtree(OUT)
    total = 0
    for kind, root, ext in (("typ", DOCS, ".typ"), ("rs", CRATES, ".rs")):
        for base, dirs, names in sorted(os.walk(root)):
            dirs.sort()
            for name in sorted(names):
                if not name.endswith(ext):
                    continue
                path = os.path.join(base, name)
                lines = open(path, encoding="utf-8").read().split("\n")
                if kind == "rs":
                    # Doc comment lines; anything else ends a block.
                    doc = []
                    for l in lines:
                        s = l.lstrip()
                        if s.startswith("///"):
                            s = s[3:]
                            doc.append(s[1:] if s.startswith(" ") else s)
                        else:
                            doc.append("\x00")
                    lines = doc
                cases = []
                for line_no, body in blocks(lines):
                    if any("\x00" in l for l in body):
                        continue
                    text = source(body)
                    if text is None:
                        continue
                    cases.append((line_no, text))
                if not cases:
                    continue
                rel = os.path.relpath(path, root)
                stem = re.sub(r"[^A-Za-z0-9]+", "-", rel[:-len(ext)]).strip("-")
                out = os.path.join(OUT, kind, stem + ".typ")
                os.makedirs(os.path.dirname(out), exist_ok=True)
                with open(out, "w", encoding="utf-8") as f:
                    f.write(f"// Examples of {rel} (generated by scripts/edsl_docs_examples.py).\n\n")
                    for line_no, text in cases:
                        f.write(f"--- {stem}-l{line_no} paged ---\n{text}\n")
                total += len(cases)
    print(f"{total} examples in {OUT}")


if __name__ == "__main__":
    main()
