#!/usr/bin/env python3
"""Generate the data tables of the shaper (`shape/`) from the rustybuzz
sources they are ported from (rustybuzz's own generated tables).

Usage: gen_shape_tables.py [rustybuzz checkout, default .repos/rustybuzz]

Writes `shape/*_gen.mbt`. Never edit those by hand.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RB = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '.repos', 'rustybuzz')
HB = os.path.join(RB, 'src', 'hb')
OUT = os.path.join(ROOT, 'shape')

HEADER = '// Generated by scripts/gen_shape_tables.py from rustybuzz `src/hb/%s`.\n// Do not edit.\n\n'


def read(name):
    return open(os.path.join(HB, name), encoding='utf-8').read()


def char_lit(s):
    """Value of a Rust char literal body like `\\u{00C0}` or `a`."""
    m = re.fullmatch(r"\\u\{([0-9A-Fa-f]+)\}", s)
    if m:
        return int(m.group(1), 16)
    assert len(s) == 1, s
    return ord(s)


def emit_ints(name, doc, values, per_line=8, typ='FixedArray[Int]'):
    out = ['///|\n/// %s\nlet %s : %s = [\n' % (doc, name, typ)]
    for i in range(0, len(values), per_line):
        out.append('  ' + ' '.join('%s,' % v for v in values[i:i + per_line]) + '\n')
    out.append(']\n\n')
    return ''.join(out)


def body_of(src, start_marker):
    i = src.index(start_marker)
    i = src.index('[', src.index('=', i)) + 1
    depth = 1
    j = i
    while depth:
        c = src[j]
        if c == '[':
            depth += 1
        elif c == ']':
            depth -= 1
        j += 1
    return src[i:j - 1]


def gen_unicode_norm():
    src = read('unicode_norm.rs')
    dec = body_of(src, 'pub const DECOMPOSITION_TABLE')
    rows = re.findall(r"\('((?:\\u\{[0-9A-Fa-f]+\})|.)', '((?:\\u\{[0-9A-Fa-f]+\})|.)', (None|Some\('((?:\\u\{[0-9A-Fa-f]+\})|.)'\))\)", dec)
    flat = []
    for a, b, opt, c in rows:
        flat += ['0x%X' % char_lit(a), '0x%X' % char_lit(b), '0x%X' % (char_lit(c) if opt != 'None' else 0)]
    assert len(rows) == dec.count('\n    ('), 'decomposition rows'
    comp = body_of(src, 'pub const COMPOSITION_TABLE')
    crow = re.findall(r"\((\d+), '((?:\\u\{[0-9A-Fa-f]+\})|.)'\)", comp)
    assert len(crow) == comp.count('\n    ('), 'composition rows'
    cflat = []
    for needle, c in crow:
        n = int(needle)
        cflat += ['0x%X' % (n >> 32), '0x%X' % (n & 0xFFFFFFFF), '0x%X' % char_lit(c)]
    out = HEADER % 'unicode_norm.rs'
    out += emit_ints('decomposition_table', 'Canonical decompositions `[ab, a, b or 0]`, sorted by `ab`.', flat, 9)
    out += emit_ints('composition_table', 'Canonical compositions `[a, b, ab]`, sorted by `(a, b)`.', cflat, 9)
    open(os.path.join(OUT, 'unicode_norm_gen.mbt'), 'w').write(out)


def gen_emoji():
    src = read('unicode.rs')
    i = src.index('fn is_emoji_extended_pictographic')
    j = src.index('_ => false', i)
    ranges = []
    for m in re.finditer(r'0x([0-9A-F]+)(?:\.\.=0x([0-9A-F]+))? => true', src[i:j]):
        lo = int(m.group(1), 16)
        hi = int(m.group(2), 16) if m.group(2) else lo
        ranges += ['0x%X' % lo, '0x%X' % hi]
    out = HEADER % 'unicode.rs (is_emoji_extended_pictographic)'
    out += emit_ints('emoji_extended_pictographic_table', 'Extended_Pictographic ranges `[lo, hi]` (gen-unicode-is-emoji-ext-pict.py).', ranges, 8)
    open(os.path.join(OUT, 'unicode_emoji_gen.mbt'), 'w').write(out)


# --- Indic family: ot_shaper_indic_table.rs and the Ragel machines ---------

def indic_constants():
    """`ot_category_t` / `ot_position_t` values from ot_shaper_indic.rs."""
    src = read('ot_shaper_indic.rs')
    consts = {}
    for name, val in re.findall(r'pub const (\w+): u8 = (\w+);', src):
        consts[name] = int(val) if val.isdigit() else consts[val]
    return consts


def gen_indic_table():
    src = read('ot_shaper_indic_table.rs')
    consts = indic_constants()
    alias = dict((a, n) for n, a in re.findall(r'use (\w+)\s+as (_\w+);', src))
    for a, n in alias.items():
        assert n in consts, n
    i = src.index('const TABLE: &[(SyllabicCategory, MatraCategory)] = &[')
    j = src.index('\n];', i)
    body = src[i:j]
    lines = []
    count = 0
    for line in body.split('\n')[1:]:
        line = line.strip()
        if not line:
            continue
        m = re.fullmatch(r'/\* ([0-9A-F]+) \*/\s*(.*)', line)
        if m:
            pairs = re.findall(r'\((_\w+),\s*(_\w+)\)', m.group(2))
            assert len(pairs) == m.group(2).count('('), line
            count += len(pairs)
            lines.append('  // %s\n  %s\n' % (m.group(1), ' '.join(
                '(%s, %s),' % (alias[c], alias[p]) for c, p in pairs)))
            continue
        m = re.fullmatch(r'/\* (.+) \*/', line)
        assert m, line
        lines.append('\n  // %s\n\n' % m.group(1))
    offsets = re.findall(r'const (OFFSET_\w+): usize = (\d+);', src)
    out = HEADER % 'ot_shaper_indic_table.rs'
    out += '///|\n/// `(SyllabicCategory, MatraCategory)` per code point of the covered ranges.\n'
    out += 'let indic_table : FixedArray[(Int, Int)] = [\n'
    out += ''.join(lines)
    out += ']\n\n'
    for name, val in offsets:
        out += '///|\nconst %s : Int = %s\n\n' % (name, val)
    # get_categories
    i = src.index('pub fn get_categories(u: u32)')
    j = src.index('\n}', i)
    fbody = src[i:j]
    code = ['///|\nfn get_categories(u : Int) -> (Int, Int) {\n', '  match u >> 12 {\n']
    for line in fbody.split('\n')[2:]:
        if line == '    }':  # end of `match u >> 12`
            continue
        line = line.strip()
        if not line or line == '_ => {}':
            continue
        if line == '(_OT_X, _POS_X)':
            break
        if line == '}':
            code.append('    }\n')
            continue
        m = re.fullmatch(r'(0x[0-9A-F]+) => \{', line)
        if m:
            code.append('    %s => {\n' % m.group(1))
            continue
        m = re.fullmatch(r'if u == (0x[0-9A-F]+) \{ return \((_\w+), (_\w+)\); \}', line)
        if m:
            code.append('      if u == %s {\n        return (%s, %s)\n      }\n' % (
                m.group(1), alias[m.group(2)], alias[m.group(3)]))
            continue
        m = re.fullmatch(r'if \((0x[0-9A-F]+)\.\.=(0x[0-9A-F]+)\)\.contains\(&u\) \{ return TABLE\[u as usize - (0x[0-9A-F]+) \+ (OFFSET_\w+)\]; \}', line)
        assert m, line
        assert m.group(1) == m.group(3)
        code.append('      if u >= %s && u <= %s {\n        return indic_table[u - %s + %s]\n      }\n' % (
            m.group(1), m.group(2), m.group(1), m.group(4)))
    code.append('    _ => ()\n  }\n  (OT_X, POS_END)\n}\n')
    out += ''.join(code)
    open(os.path.join(OUT, 'ot_shaper_indic_table_gen.mbt'), 'w').write(out)


def gen_machine(name):
    """Data tables of the Ragel-generated `ot_shaper_<name>_machine.rs`."""
    src = read('ot_shaper_%s_machine.rs' % name)
    out = HEADER % ('ot_shaper_%s_machine.rs' % name)
    for var, typ, n, body in re.findall(r'static (\w+): \[(\w+); (\d+)\] = \[([^\]]*)\];', src):
        vals = [v.strip() for v in body.split(',') if v.strip()]
        assert len(vals) == int(n), var
        out += emit_ints(var.lstrip('_'), '`%s: [%s; %s]`' % (var, typ, n), vals, 20)
    for var, val in re.findall(r'static (\w+): i32 = (-?\d+);', src):
        out += '///|\nlet %s : Int = %s\n\n' % (var, val)
    open(os.path.join(OUT, 'ot_shaper_%s_machine_gen.mbt' % name), 'w').write(out)


if __name__ == '__main__':
    gen_unicode_norm()
    gen_emoji()
    gen_indic_table()
    for name in ['indic', 'khmer', 'myanmar']:
        gen_machine(name)
