#!/usr/bin/env python3
"""Generate the data tables of the shaper (`shape/`) from the rustybuzz
sources they are ported from (rustybuzz's own generated tables).

Usage: gen_shape_tables.py [rustybuzz checkout, default .repos/rustybuzz]

Writes `shape/*_gen.mbt`. Never edit those by hand.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RB = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '.repos', 'rustybuzz')
HB = os.path.join(RB, 'src', 'hb')
OUT = os.path.join(ROOT, 'shape')

HEADER = '// Generated by scripts/gen_shape_tables.py from rustybuzz `src/hb/%s`.\n// Do not edit.\n\n'


def read(name):
    return open(os.path.join(HB, name), encoding='utf-8').read()


def char_lit(s):
    """Value of a Rust char literal body like `\\u{00C0}` or `a`."""
    m = re.fullmatch(r"\\u\{([0-9A-Fa-f]+)\}", s)
    if m:
        return int(m.group(1), 16)
    assert len(s) == 1, s
    return ord(s)


def emit_ints(name, doc, values, per_line=8, typ='FixedArray[Int]'):
    out = ['///|\n/// %s\nlet %s : %s = [\n' % (doc, name, typ)]
    for i in range(0, len(values), per_line):
        out.append('  ' + ' '.join('%s,' % v for v in values[i:i + per_line]) + '\n')
    out.append(']\n\n')
    return ''.join(out)


def body_of(src, start_marker):
    i = src.index(start_marker)
    i = src.index('[', src.index('=', i)) + 1
    depth = 1
    j = i
    while depth:
        c = src[j]
        if c == '[':
            depth += 1
        elif c == ']':
            depth -= 1
        j += 1
    return src[i:j - 1]


def gen_unicode_norm():
    src = read('unicode_norm.rs')
    dec = body_of(src, 'pub const DECOMPOSITION_TABLE')
    rows = re.findall(r"\('((?:\\u\{[0-9A-Fa-f]+\})|.)', '((?:\\u\{[0-9A-Fa-f]+\})|.)', (None|Some\('((?:\\u\{[0-9A-Fa-f]+\})|.)'\))\)", dec)
    flat = []
    for a, b, opt, c in rows:
        flat += ['0x%X' % char_lit(a), '0x%X' % char_lit(b), '0x%X' % (char_lit(c) if opt != 'None' else 0)]
    assert len(rows) == dec.count('\n    ('), 'decomposition rows'
    comp = body_of(src, 'pub const COMPOSITION_TABLE')
    crow = re.findall(r"\((\d+), '((?:\\u\{[0-9A-Fa-f]+\})|.)'\)", comp)
    assert len(crow) == comp.count('\n    ('), 'composition rows'
    cflat = []
    for needle, c in crow:
        n = int(needle)
        cflat += ['0x%X' % (n >> 32), '0x%X' % (n & 0xFFFFFFFF), '0x%X' % char_lit(c)]
    out = HEADER % 'unicode_norm.rs'
    out += emit_ints('decomposition_table', 'Canonical decompositions `[ab, a, b or 0]`, sorted by `ab`.', flat, 9)
    out += emit_ints('composition_table', 'Canonical compositions `[a, b, ab]`, sorted by `(a, b)`.', cflat, 9)
    open(os.path.join(OUT, 'unicode_norm_gen.mbt'), 'w').write(out)


def gen_emoji():
    src = read('unicode.rs')
    i = src.index('fn is_emoji_extended_pictographic')
    j = src.index('_ => false', i)
    ranges = []
    for m in re.finditer(r'0x([0-9A-F]+)(?:\.\.=0x([0-9A-F]+))? => true', src[i:j]):
        lo = int(m.group(1), 16)
        hi = int(m.group(2), 16) if m.group(2) else lo
        ranges += ['0x%X' % lo, '0x%X' % hi]
    out = HEADER % 'unicode.rs (is_emoji_extended_pictographic)'
    out += emit_ints('emoji_extended_pictographic_table', 'Extended_Pictographic ranges `[lo, hi]` (gen-unicode-is-emoji-ext-pict.py).', ranges, 8)
    open(os.path.join(OUT, 'unicode_emoji_gen.mbt'), 'w').write(out)


if __name__ == '__main__':
    gen_unicode_norm()
    gen_emoji()
