#!/usr/bin/env python3
"""Generate the hayro-interpret font tables and embedded assets.

Translates the `phf` tables of hayro-interpret's `src/font/generated/*.rs`
(glyph names, encodings and standard font metrics) into
`hayro/interpret/font_generated_gen.mbt`, and embeds hayro-interpret's ICC
profiles (`assets/LAB.icc`, `assets/CGATS001Compat-v2-micro.icc`) into
`hayro/interpret/assets_gen.mbt`.

Usage: python3 scripts/gen_hayro_tables.py [path/to/hayro checkout]
(default: the cargo git checkout of the pinned hayro revision).
"""

import base64
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REV = "d8e24e2"


def find_hayro():
    pattern = os.path.expanduser(f"~/.cargo/git/checkouts/hayro-*/{REV}")
    found = sorted(glob.glob(pattern))
    if not found:
        sys.exit("hayro checkout not found; pass its path")
    return found[-1]


ENTRY = re.compile(r"^\s*(.+?)\s*=>\s*(.+?),\s*$")


def parse_maps(path):
    """Returns {static name: [(key, value)]} of the `phf_map!`s in a file."""
    maps = {}
    cur = None
    for line in open(path, encoding="utf-8"):
        m = re.match(r"^(?:pub\(crate\) )?static (\w+): phf::Map<", line)
        if m:
            cur = m.group(1)
            maps[cur] = []
            continue
        if cur is None:
            continue
        if line.startswith("};"):
            cur = None
            continue
        m = ENTRY.match(line)
        if m:
            maps[cur].append((m.group(1), m.group(2)))
    return maps


def rust_str(lit):
    """Decodes a Rust string or char literal."""
    assert lit[0] in "\"'" and lit[-1] == lit[0], lit
    body = lit[1:-1]
    out = []
    i = 0
    while i < len(body):
        c = body[i]
        if c == "\\":
            n = body[i + 1]
            if n == "u":
                j = body.index("}", i)
                out.append(chr(int(body[i + 3 : j], 16)))
                i = j + 1
                continue
            out.append({"n": "\n", "t": "\t", "\\": "\\", '"': '"', "'": "'", "0": "\0"}[n])
            i += 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


def mbt_str(s):
    out = ['"']
    for c in s:
        o = ord(c)
        if c == '"' or c == "\\":
            out.append("\\" + c)
        elif 0x20 <= o < 0x7F:
            out.append(c)
        else:
            out.append("\\u{%x}" % o)
    out.append('"')
    return "".join(out)


def u8_key(lit):
    m = re.match(r"^(\d+)_u8$", lit)
    assert m, lit
    return int(m.group(1))


def f32_val(lit):
    m = re.match(r"^(-?[\d.]+)_f32$", lit)
    assert m, lit
    v = m.group(1)
    return v if "." in v else v + ".0"


def gen_tables(hayro):
    gen = os.path.join(hayro, "hayro-interpret/src/font/generated")
    out = []
    out.append(
        "// Generated by scripts/gen_hayro_tables.py from hayro-interpret's\n"
        "// `src/font/generated/*.rs`. Do not edit.\n"
    )

    def code_table(fn_prefix, entries, doc):
        arr = ["None"] * 256
        for k, v in entries:
            arr[u8_key(k)] = "Some(%s)" % mbt_str(rust_str(v))
        out.append("///|\n/// %s\nlet %s_table : FixedArray[String?] = [\n" % (doc, fn_prefix))
        for i in range(0, 256, 4):
            out.append("  " + ", ".join(arr[i : i + 4]) + ",\n")
        out.append("]\n\n")
        out.append(
            "///|\nfn %s_get(code : Byte) -> String? {\n  %s_table[code.to_int()]\n}\n\n"
            % (fn_prefix, fn_prefix)
        )

    def inverse_table(fn_prefix, entries, doc):
        out.append(
            "///|\n/// %s\nlet %s_inverse_table : Map[String, Byte] = {\n" % (doc, fn_prefix)
        )
        for k, v in entries:
            out.append("  %s: %d,\n" % (mbt_str(rust_str(k)), int(re.match(r"^(\d+)", v).group(1))))
        out.append("}\n\n")
        out.append(
            "///|\nfn %s_get_inverse(name : String) -> Byte? {\n  %s_inverse_table.get(name)\n}\n\n"
            % (fn_prefix, fn_prefix)
        )

    for mod, static, doc in [
        ("standard", "STANDARD", "The standard encoding."),
        ("mac_expert", "MAC_EXPERT", "The MacExpert encoding."),
        ("symbol", "SYMBOL", "The built-in encoding of the Symbol font."),
        ("win_ansi", "WIN_ANSI", "The WinAnsi encoding."),
        ("zapf_dings", "ZAPF_DING_BATS", "The built-in encoding of the ZapfDingbats font."),
        ("mac_roman", "MAC_ROMAN", "The MacRoman encoding."),
        ("mac_os_roman", "MAC_OS_ROMAN", "The Mac OS Roman additions to MacRoman."),
    ]:
        maps = parse_maps(os.path.join(gen, mod + ".rs"))
        code_table(mod, maps[static], doc)
        inv = static + "_INVERSE"
        if inv in maps:
            inverse_table(mod, maps[inv], "Inverse of the " + mod + " table.")

    maps = parse_maps(os.path.join(gen, "glyph_names.rs"))
    out.append("///|\n/// The Adobe Glyph List.\nlet glyph_names_table : Map[String, String] = {\n")
    for k, v in maps["GLYPH_NAMES"]:
        out.append("  %s: %s,\n" % (mbt_str(rust_str(k)), mbt_str(rust_str(v))))
    out.append("}\n\n")
    out.append(
        "///|\nfn glyph_names_get(name : String) -> String? {\n  glyph_names_table.get(name)\n}\n\n"
    )
    out.append(
        "///|\n/// The reverse Adobe Glyph List.\nlet reverse_glyph_names_table : Map[Char, String] = {\n"
    )
    for k, v in maps["REVERSE_GLYPH_NAMES"]:
        out.append("  %s: %s,\n" % (mbt_char(rust_str(k)), mbt_str(rust_str(v))))
    out.append("}\n\n")
    out.append(
        "///|\nfn glyph_names_get_reverse(unicode : Char) -> String? {\n"
        "  reverse_glyph_names_table.get(unicode)\n}\n\n"
    )

    maps = parse_maps(os.path.join(gen, "metrics.rs"))
    for static, entries in maps.items():
        name = "metrics_" + static.lower()
        out.append("///|\nlet %s : Map[String, Float] = {\n" % name)
        for k, v in entries:
            out.append("  %s: %s,\n" % (mbt_str(rust_str(k)), f32_val(v)))
        out.append("}\n\n")

    path = os.path.join(ROOT, "hayro/interpret/font_generated_gen.mbt")
    open(path, "w", encoding="utf-8").write("".join(out))


def mbt_char(s):
    assert len(s) == 1
    o = ord(s)
    if s == "'" or s == "\\":
        return "'\\%s'" % s
    if 0x20 <= o < 0x7F:
        return "'%s'" % s
    return "'\\u{%x}'" % o


def gen_assets(hayro):
    out = [
        "// Generated by scripts/gen_hayro_tables.py from hayro-interpret's\n"
        "// `assets/`. Do not edit.\n\n"
    ]
    for name, file in [
        ("lab_icc", "LAB.icc"),
        ("cgats001_compat_v2_micro_icc", "CGATS001Compat-v2-micro.icc"),
    ]:
        data = open(os.path.join(hayro, "hayro-interpret/assets", file), "rb").read()
        b64 = base64.b64encode(data).decode()
        out.append("///|\n/// `assets/%s` (base64).\nlet %s_base64 : String =\n" % (file, name))
        chunks = [b64[i : i + 96] for i in range(0, len(b64), 96)]
        for c in chunks:
            out.append('  #|%s\n' % c)
        out.append("\n")
    path = os.path.join(ROOT, "hayro/interpret/assets_gen.mbt")
    open(path, "w", encoding="utf-8").write("".join(out))


PDF_FONTS = [
    ("ding_bats", "FoxitDingbats.pfb", "Foxit Ding Bats Font."),
    ("symbol", "FoxitSymbol.pfb", "Foxit Symbol Font."),
    ("fixed", "FoxitFixed.pfb", "Foxit Fixed font."),
    ("fixed_bold", "FoxitFixedBold.pfb", "Foxit Fixed Bold font."),
    ("fixed_bold_italic", "FoxitFixedBoldItalic.pfb", "Foxit Fixed Bold Italic font."),
    ("fixed_italic", "FoxitFixedItalic.pfb", "Foxit Fixed Italic font."),
    ("sans", "FoxitSans.pfb", "Foxit Sans font."),
    ("sans_bold", "FoxitSansBold.pfb", "Foxit Sans Bold font."),
    ("sans_bold_italic", "FoxitSansBoldItalic.pfb", "Foxit Sans Bold Italic font."),
    ("sans_italic", "FoxitSansItalic.pfb", "Foxit Sans Italic font."),
    ("serif", "FoxitSerif.pfb", "Foxit Serif font."),
    ("serif_bold", "FoxitSerifBold.pfb", "Foxit Serif Bold font."),
    ("serif_bold_italic", "FoxitSerifBoldItalic.pfb", "Foxit Serif Bold Italic font."),
    ("serif_italic", "FoxitSerifItalic.pfb", "Foxit Serif Italic font."),
]


def find_typst_assets():
    pattern = os.path.expanduser("~/.cargo/git/checkouts/typst-assets-*/94dcb99/files")
    found = sorted(glob.glob(pattern))
    if not found:
        sys.exit("typst-assets checkout not found")
    return found[-1]


def gen_pdf_fonts():
    """Embeds typst-assets' `pdf` fonts (the PDF standard font substitutes)."""
    files = find_typst_assets()
    out = [
        "// Generated by scripts/gen_hayro_tables.py from typst-assets'\n"
        "// `files/fonts/Foxit*.pfb` (`typst_assets::pdf`). Do not edit.\n\n"
    ]
    for name, file, doc in PDF_FONTS:
        data = open(os.path.join(files, "fonts", file), "rb").read()
        b64 = base64.b64encode(data).decode()
        out.append("///|\nlet %s_base64 : String =\n" % name)
        for i in range(0, len(b64), 96):
            out.append("  #|%s\n" % b64[i : i + 96])
        out.append("\n")
        out.append("///|\nlet %s_cell : Ref[Bytes?] = Ref::new(None)\n\n" % name)
        out.append(
            "///|\n/// %s\npub fn %s() -> Bytes {\n  load(%s_cell, %s_base64)\n}\n\n"
            % (doc, name, name, name)
        )
    path = os.path.join(ROOT, "typst_assets/pdf/fonts_gen.mbt")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w", encoding="utf-8").write("".join(out))


def main():
    hayro = sys.argv[1] if len(sys.argv) > 1 else find_hayro()
    gen_tables(hayro)
    gen_assets(hayro)
    gen_pdf_fonts()


if __name__ == "__main__":
    main()
