#!/usr/bin/env python3
"""Generate bib/hayagriva/lang_lists_gen.mbt from hayagriva's word lists.

Extracts the `&str` array constants of `src/lang/en.rs` (`ARTICLES`,
`NEVER_CAPITALIZE`, `ALWAYS_CAPITALIZE`) and `src/lang/name.rs`
(`NAME_PARTICLES`) of the hayagriva crate version pinned in typst's
Cargo.lock. Upstream looks them up with `binary_search`; the generated file
records whether each list is sorted (in Rust `str` order) so the port can
mirror the lookup exactly.

Usage: python3 scripts/gen_hayagriva_lists.py
"""

import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def crate_dir():
    lock = open(os.path.join(ROOT, ".repos/typst/Cargo.lock")).read()
    m = re.search(r'name = "hayagriva"\nversion = "([^"]+)"', lock)
    version = m.group(1)
    pattern = os.path.expanduser(
        f"~/.cargo/registry/src/*/hayagriva-{version}/src/lang")
    dirs = glob.glob(pattern)
    if not dirs:
        sys.exit(f"hayagriva {version} not found in the cargo registry")
    return dirs[0], version


def lists(path):
    src = open(path).read()
    for m in re.finditer(
            r'pub const (\w+): \[&str; (\d+)\] = \[(.*?)\];', src, re.S):
        name, n, body = m.group(1), int(m.group(2)), m.group(3)
        items = re.findall(r'"((?:[^"\\]|\\.)*)"', body)
        assert len(items) == n, (name, len(items), n)
        yield name, items


def mbt_lit(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def main():
    d, version = crate_dir()
    out = [
        f"// Generated by scripts/gen_hayagriva_lists.py from hayagriva {version}",
        "// (`src/lang/en.rs`, `src/lang/name.rs`). Do not edit by hand!",
        "",
    ]
    for f in ["en.rs", "name.rs"]:
        for name, items in lists(os.path.join(d, f)):
            enc = [s.encode("utf-8") for s in items]
            is_sorted = all(enc[i] <= enc[i + 1] for i in range(len(enc) - 1))
            out.append("///|")
            out.append(f"/// `{name}` (sorted: {str(is_sorted).lower()}).")
            out.append(f"let {name.lower()} : Array[String] = [")
            for s in items:
                out.append(f"  {mbt_lit(s)},")
            out.append("]")
            out.append("")
    path = os.path.join(ROOT, "bib/hayagriva/lang_lists_gen.mbt")
    open(path, "w").write("\n".join(out))
    print("wrote", path)


main()
