#!/usr/bin/env python3
"""Generate `library/translations_gen.mbt` from upstream's translation files.

Mirrors `TRANSLATIONS` and `parse_language_bundle` of
`typst-library/src/text/lang.rs`: the list of bundles is taken from the
`translation!(..)` entries in `lang.rs`, and each file is parsed like upstream
(comment lines starting with `#` are skipped, `key = value` pairs are trimmed).
"""

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIB = os.path.join(ROOT, ".repos", "typst", "crates", "typst-library")


def parse(text):
    bundle = []
    keys = set()
    for line in text.strip().splitlines():
        if line.strip().startswith("#"):
            continue
        if "=" not in line:
            raise SystemExit('malformed translation file: line without "="')
        key, val = line.split("=", 1)
        key, val = key.strip(), val.strip()
        if not val:
            raise SystemExit("malformed translation file: empty translation value")
        if key in keys:
            raise SystemExit("malformed translation file: duplicate key")
        keys.add(key)
        bundle.append((key, val))
    return bundle


def main():
    src = open(os.path.join(LIB, "src", "text", "lang.rs")).read()
    names = re.findall(r'translation!\("([^"]+)"\)', src)
    out = [
        "// Generated by scripts/gen_translations.py from the translation files of\n"
        "// typst-library. Do not edit.\n\n",
        "///|\n/// The translation bundles (upstream `TRANSLATIONS`, parsed like\n"
        "/// `parse_language_bundle`).\n",
        "let translations : ReadOnlyArray[(String, ReadOnlyArray[(String, String)])] = [\n",
    ]
    for name in names:
        text = open(os.path.join(LIB, "translations", name + ".txt"), encoding="utf-8").read()
        pairs = ", ".join(f"({json.dumps(k, ensure_ascii=False)}, {json.dumps(v, ensure_ascii=False)})" for k, v in parse(text))
        out.append(f"  ({json.dumps(name)}, [{pairs}]),\n")
    out.append("]\n")
    with open(os.path.join(ROOT, "library", "translations_gen.mbt"), "w", encoding="utf-8") as f:
        f.write("".join(out))
    print(f"{len(names)} translation bundles")


if __name__ == "__main__":
    main()
