#!/usr/bin/env python3
"""Generate doc/review_page_gen.mbt from doc/review_page/{page.css,page.js,page.html}.

The preview page of the EDSL review loop (docs/edsl-review.md, section 8) is
self-contained: its style sheet, script and markup are string constants of
the `doc` package. Edit the three files and rerun this script:

    python3 scripts/gen_review_page.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "doc", "review_page")
OUT = os.path.join(ROOT, "doc", "review_page_gen.mbt")


def constant(name, doc, text):
    lines = ["///|", "/// " + doc, "let %s : String =" % name]
    for line in text.split("\n"):
        # A raw multi-line string: nothing is escaped.
        lines.append("  #|" + line)
    return "\n".join(lines) + "\n"


def main():
    css = open(os.path.join(SRC, "page.css"), encoding="utf-8").read()
    js = open(os.path.join(SRC, "page.js"), encoding="utf-8").read()
    html = open(os.path.join(SRC, "page.html"), encoding="utf-8").read()
    for name, text in (("page.css", css), ("page.js", js), ("page.html", html)):
        if "</script" in text or "</style" in text:
            raise SystemExit("%s must not contain a closing script or style tag" % name)
    body, tail = html.split("<!--PAGES-->\n")
    out = [
        "// Generated by scripts/gen_review_page.py from doc/review_page/. DO NOT EDIT.",
        "",
        constant("review_page_css", "The style sheet of the preview page.", css),
        constant("review_page_js", "The script of the preview page.", js),
        constant(
            "review_page_body",
            "The markup before the pages (`{{TITLE}}` is the document's title).",
            body,
        ),
        constant("review_page_tail", "The markup after the pages.", tail),
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main()
