#!/usr/bin/env python3
"""Embed the texts of the `lipsum` crate (used by upstream `lorem`) as
`library/lorem_data_gen.mbt`."""
import glob, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = sorted(glob.glob(os.path.expanduser("~/.cargo/registry/src/*/lipsum-0.9.1/src")))[0]
out = ["// Generated by scripts/gen_lorem.py from lipsum 0.9.1 (MIT,", "// Copyright (c) 2017 Martin Geisler). Do not edit.", ""]
for name, file in [("lorem_ipsum_text", "lorem-ipsum.txt"), ("liber_primus_text", "liber-primus.txt")]:
    text = open(os.path.join(src, file), encoding="utf-8").read()
    out.append("///|")
    out.append(f"let {name} : String =")
    for line in text.splitlines(keepends=True):
        out.append("  #|" + line.rstrip("\n"))
    if not text.endswith("\n"):
        raise SystemExit("expected trailing newline")
    out.append("")
open(os.path.join(ROOT, "library", "lorem_data_gen.mbt"), "w").write("\n".join(out))
