#!/usr/bin/env python3
"""Generates usvg/unicode_vo_gen.mbt from the source of the `unicode-vo` 0.1.0
crate (the Vertical_Orientation data usvg uses for `writing-mode: tb`).

Usage: python3 scripts/gen_unicode_vo.py   (from the repository root; the
crate is looked up in ~/.cargo/registry/src/*/unicode-vo-0.1.0)."""
import glob
import os
import re

paths = glob.glob(os.path.expanduser('~/.cargo/registry/src/*/unicode-vo-0.1.0/src/lib.rs'))
src = open(paths[0]).read()
arms = re.findall(r'^\s*(0x[0-9A-F]+)(?:\.\.\.(0x[0-9A-F]+))? => Orientation::(\w+),', src, re.M)
out = ['// Generated by scripts/gen_unicode_vo.py from the `unicode-vo` 0.1.0 crate',
       '// (`src/lib.rs`, revision 17 of the Unicode Vertical_Orientation data)',
       '// used by usvg. Do not edit.', '',
       '///|', '/// Character orientation (`unicode_vo::Orientation`).',
       'priv enum VerticalOrientation {', '  Upright', '  Rotated', '  TransformedOrUpright',
       '  TransformedOrRotated', '} derive(Eq)', '',
       '///|', '/// The ranges of `unicode_vo::char_orientation` (start, end, orientation).',
       'let vertical_orientation_ranges : Array[(Int, Int, VerticalOrientation)] = [']
for lo, hi, o in arms:
    out.append('  (%s, %s, %s),' % (lo, hi or lo, o))
out += [']', '', '///|',
        '/// Returns a vertical orientation of a character (`unicode_vo::char_orientation`).',
        'fn char_orientation(c : Char) -> VerticalOrientation {',
        '  let cp = c.to_int()',
        '  for r in vertical_orientation_ranges {',
        '    if cp >= r.0 && cp <= r.1 {',
        '      return r.2',
        '    }',
        '  }',
        '  Rotated',
        '}', '']
open('usvg/unicode_vo_gen.mbt', 'w').write('\n'.join(out))
print(len(arms), 'ranges')
