#!/usr/bin/env python3
"""Generate `wasmi/engine_translator_func_dispatch_gen.mbt`: the dispatch of a
decoded `@wasmparser.Operator` to the `FuncTranslator::visit_*` method of the
same name (upstream's `VisitOperator` implementation of `FuncTranslator`,
visit.rs and simd/visit.rs). Operators of proposals the translator does not
implement are routed to `translate_unsupported_operator`, like upstream.

Usage: python3 scripts/gen_wasmi_visit_dispatch.py
"""

import glob
import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
OPS = os.path.join(ROOT, "wasmparser", "readers_core_operators_gen.mbt")
OUT = os.path.join(ROOT, "wasmi", "engine_translator_func_dispatch_gen.mbt")


def main():
    text = open(OPS).read()
    enum = re.search(r"pub\(all\) enum Operator \{\n(.*?)\n\}", text, re.S).group(1)
    variants = []
    lines = []
    cur = ""
    for line in enum.split("\n"):
        line = line.strip()
        if not line or line.startswith("//"):
            continue
        cur = (cur + " " + line).strip() if cur else line
        if cur.count("(") == cur.count(")"):
            lines.append(cur.replace("( ", "(").replace(", )", ")").replace(",)", ")"))
            cur = ""
    for line in lines:
        m = re.match(r"^(\w+)(?:\((.*)\))?$", line)
        assert m, line
        fields = []
        if m.group(2):
            for part in m.group(2).split(","):
                fm = re.match(r"\s*(\w+)~\s*:\s*(.+)\s*", part)
                assert fm, part
                fields.append((fm.group(1), fm.group(2).strip()))
        variants.append((m.group(1), fields))
    visit_names = dict(re.findall(r"^\s+(\w+)(?:\(\.\.\))? => \"(visit_\w+)\"", text, re.M))
    # The visit methods implemented by the MoonBit translator.
    implemented = set()
    for path in glob.glob(os.path.join(ROOT, "wasmi", "engine_translator_func*.mbt")):
        if path == OUT:
            continue
        implemented.update(re.findall(r"fn FuncTranslator::(visit_\w+)\(", open(path).read()))
    out = []
    w = out.append
    w("// Generated by scripts/gen_wasmi_visit_dispatch.py. Do not edit by hand.")
    w("")
    w("///|")
    w("/// Visits a decoded Wasm operator (upstream `VisitOperator for FuncTranslator`).")
    w("pub fn FuncTranslator::visit_operator(")
    w("  self : FuncTranslator,")
    w("  op : @wasmparser.Operator,")
    w(") -> Unit raise Error {")
    w("  match op {")
    missing = []
    for name, fields in variants:
        visit = visit_names.get(name)
        binds = ", ".join(f"{f}~" for f, _ in fields)
        pat = f"{name}({binds})" if fields else name
        if visit not in implemented:
            missing.append(name)
            pat = f"{name}(..)" if fields else name
            w(f'    {pat} => self.translate_unsupported_operator("{name}")')
            continue
        args = []
        for f, ty in fields:
            if ty == "Ieee32" or ty == "Ieee64":
                args.append(f"{f}.bits()")
            elif ty == "V128":
                args.append(f"{f}.bytes().to_fixedarray()")
            elif ty == "Byte":
                args.append(f"{f}.to_int()")
            else:
                args.append(f)
        w(f"    {pat} => self.{visit}({', '.join(args)})")
    w("  }")
    w("}")
    w("")
    open(OUT, "w").write("\n".join(out))
    print(f"wrote {OUT}: {len(variants)} operators, {len(missing)} unsupported")


if __name__ == "__main__":
    main()
