#!/usr/bin/env python3
"""Generates the operator tables of the wasmparser port (wasmparser/).

Reads the single source of truth of wasmparser 0.228.0, the
`_for_each_operator_group!` macro in `src/lib.rs`, and emits:

- `wasmparser/readers_core_operators_gen.mbt`: the `Operator` enum
  (`define_operator!` in `readers/core/operators.rs`) and
  `Operator::proposal`/`Operator::visit_name`.
- `wasmparser/validator_operators_gen.mbt`: `WasmProposalValidator` (the
  `validate_proposal!` macro of `validator/operators.rs`): one `visit_*`
  method per operator that checks the operator's proposal is enabled and
  delegates to `OperatorValidatorTemp`, plus `visit_operator` dispatching an
  `Operator` (`VisitOperator::visit_operator`).
- `wasmparser/validator_core_gen.mbt`: the `VisitConstOperator` dispatch of
  `ModuleState::check_const_expr` (`validator/core.rs`).
- `wasmparser/validator_operators_todo_gen.mbt`: stubs for the
  `OperatorValidatorTemp::visit_*` methods that are not ported (yet). Their
  proposals (gc, legacy exceptions, stack switching, shared-everything
  threads) are disabled for wasmi, so the proposal check rejects them before
  the stub runs.

Usage: python3 scripts/gen_wasmparser_ops.py [path/to/wasmparser-0.228.0]
"""

import glob
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
OUT = os.path.join(ROOT, "wasmparser")


def find_crate():
    if len(sys.argv) > 1:
        return sys.argv[1]
    home = os.path.expanduser("~/.cargo/registry/src")
    cands = sorted(glob.glob(os.path.join(home, "*", "wasmparser-0.228.0")))
    if not cands:
        sys.exit("wasmparser-0.228.0 not found in ~/.cargo/registry/src")
    return cands[0]


TYPES = {
    "u32": "UInt",
    "i32": "Int",
    "i64": "Int64",
    "u8": "Byte",
    "[u8; 16]": "FixedArray[Byte]",
    "$crate::MemArg": "MemArg",
    "$crate::BlockType": "BlockType",
    "$crate::BrTable<'a>": "BrTable",
    "$crate::Ieee32": "Ieee32",
    "$crate::Ieee64": "Ieee64",
    "$crate::V128": "V128",
    "$crate::HeapType": "HeapType",
    "$crate::RefType": "RefType",
    "$crate::ValType": "ValType",
    "$crate::Ordering": "Ordering",
    "$crate::TryTable": "TryTable",
    "$crate::ResumeTable": "ResumeTable",
}

# `validate_proposal!(desc ...)`.
DESC = {
    "simd": "SIMD",
    "relaxed_simd": "relaxed SIMD",
    "threads": "threads",
    "shared_everything_threads": "shared-everything-threads",
    "saturating_float_to_int": "saturating float to int conversions",
    "reference_types": "reference types",
    "bulk_memory": "bulk memory",
    "sign_extension": "sign extension operations",
    "exceptions": "exceptions",
    "tail_call": "tail calls",
    "function_references": "function references",
    "memory_control": "memory control",
    "gc": "gc",
    "legacy_exceptions": "legacy exceptions",
    "stack_switching": "stack switching",
    "wide_arithmetic": "wide arithmetic",
}


def parse_ops(lib_rs):
    text = open(lib_rs).read()
    start = text.index("macro_rules! _for_each_operator_group")
    end = text.index("macro_rules! define_for_each_non_simd_operator")
    body = text[start:end]
    # Drop comments.
    body = re.sub(r"//[^\n]*", "", body)
    ops = []
    group_re = re.compile(r"@(\w+)\s*\{")
    pos = 0
    while True:
        m = group_re.search(body, pos)
        if not m:
            break
        proposal = m.group(1)
        # Find the matching close brace of the group.
        depth = 1
        i = m.end()
        while depth:
            if body[i] == "{":
                depth += 1
            elif body[i] == "}":
                depth -= 1
            i += 1
        group = body[m.end() : i - 1]
        pos = i
        op_re = re.compile(
            r"(\w+)\s*(?:\{([^}]*)\})?\s*=>\s*(visit_\w+)\s*\(([^)]*)\)", re.S
        )
        for om in op_re.finditer(group):
            name, fields, visit, ann = om.groups()
            fl = []
            if fields:
                for f in fields.split(","):
                    f = f.strip()
                    if not f:
                        continue
                    fname, fty = [x.strip() for x in f.split(":", 1)]
                    fl.append((fname, TYPES[fty]))
            ops.append((proposal, name, fl, visit))
    return ops


HEADER = "// Generated by scripts/gen_wasmparser_ops.py from wasmparser 0.228.0's\n// `_for_each_operator_group!` (src/lib.rs). Do not edit.\n\n"


def gen_operator(ops):
    out = [HEADER]
    out.append("///|\n/// Instructions as defined [here].\n///\n")
    out.append("/// [here]: https://webassembly.github.io/spec/core/binary/instructions.html\n")
    out.append("pub(all) enum Operator {\n")
    for proposal, name, fields, visit in ops:
        if fields:
            args = ", ".join(f"{f}~ : {t}" for f, t in fields)
            out.append(f"  {name}({args})\n")
        else:
            out.append(f"  {name}\n")
    out.append("} derive(Eq, Debug)\n\n")
    # proposal / visit name accessors
    out.append("///|\n/// The proposal (`@<proposal>` group of `for_each_operator!`) that\n/// introduced this operator.\n")
    out.append("pub fn Operator::proposal(self : Operator) -> String {\n  match self {\n")
    for proposal, name, fields, visit in ops:
        pat = f"{name}(..)" if fields else name
        out.append(f"    {pat} => \"{proposal}\"\n")
    out.append("  }\n}\n\n")
    out.append("///|\n/// The name of this operator's `visit_*` method.\n")
    out.append("pub fn Operator::visit_name(self : Operator) -> String {\n  match self {\n")
    for proposal, name, fields, visit in ops:
        pat = f"{name}(..)" if fields else name
        out.append(f"    {pat} => \"{visit}\"\n")
    out.append("  }\n}\n")
    return "".join(out)


def params(fields):
    return "".join(f", {f} : {t}" for f, t in fields)


def args(fields):
    return ", ".join(f for f, _ in fields)


def gen_validator(ops):
    out = [HEADER]
    for proposal, name, fields, visit in ops:
        out.append("///|\n")
        out.append(
            f"pub fn WasmProposalValidator::{visit}(\n  self : WasmProposalValidator{params(fields)},\n) -> Unit raise BinaryReaderError {{\n"
        )
        if proposal != "mvp":
            out.append(
                f"  self.check_enabled(self.0.inner.features.{proposal}(), \"{DESC[proposal]}\")\n"
            )
        out.append(f"  self.0.{visit}({args(fields)})\n}}\n\n")
    out.append("///|\n/// `VisitOperator::visit_operator`: validates `op`.\n")
    out.append(
        "pub fn WasmProposalValidator::visit_operator(\n  self : WasmProposalValidator,\n  op : Operator,\n) -> Unit raise BinaryReaderError {\n  match op {\n"
    )
    for proposal, name, fields, visit in ops:
        if fields:
            pat = f"{name}(" + ", ".join(f"{f}~" for f, _ in fields) + ")"
        else:
            pat = name
        out.append(f"    {pat} => self.{visit}({args(fields)})\n")
    out.append("  }\n}\n")
    return "".join(out)


# `define_visit_operator!(@visit ...)` special cases of `check_const_expr`:
# visit name -> (extra check, how to delegate). Everything else is
# `not_const(<visit name>)`.
CONST_SPECIAL = {
    "visit_i32_const": None,
    "visit_i64_const": None,
    "visit_f32_const": None,
    "visit_f64_const": None,
    "visit_v128_const": None,
    "visit_ref_null": None,
    "visit_end": None,
    "visit_i32_add": 'self.validate_extended_const("i32.add")',
    "visit_i32_sub": 'self.validate_extended_const("i32.sub")',
    "visit_i32_mul": 'self.validate_extended_const("i32.mul")',
    "visit_i64_add": 'self.validate_extended_const("i64.add")',
    "visit_i64_sub": 'self.validate_extended_const("i64.sub")',
    "visit_i64_mul": 'self.validate_extended_const("i64.mul")',
    "visit_struct_new": 'self.validate_gc("struct.new")',
    "visit_struct_new_default": 'self.validate_gc("struct.new_default")',
    "visit_array_new": 'self.validate_gc("array.new")',
    "visit_array_new_default": 'self.validate_gc("array.new_default")',
    "visit_array_new_fixed": 'self.validate_gc("array.new_fixed")',
    "visit_ref_i31": 'self.validate_gc("ref.i31")',
    "visit_ref_i31_shared": 'self.validate_shared_everything_threads("ref.i31_shared")',
    "visit_global_get": "self.validate_global(global_index)",
    "visit_ref_func": "self.insert_ref_func(function_index)",
}


def gen_const(ops):
    out = [HEADER]
    out.append(
        "///|\n/// The `VisitOperator` impl of `VisitConstOperator` (`define_visit_operator!`\n/// in `ModuleState::check_const_expr`).\n"
    )
    out.append(
        "fn VisitConstOperator::visit_operator(\n  self : VisitConstOperator,\n  op : Operator,\n) -> Unit raise BinaryReaderError {\n  match op {\n"
    )
    for proposal, name, fields, visit in ops:
        if visit not in CONST_SPECIAL:
            continue
        if fields:
            pat = f"{name}(" + ", ".join(f"{f}~" for f, _ in fields) + ")"
        else:
            pat = name
        check = CONST_SPECIAL[visit]
        call = f"self.validator().{visit}({args(fields)})"
        if check:
            out.append(f"    {pat} => {{\n      {check}\n      {call}\n    }}\n")
        else:
            out.append(f"    {pat} => {call}\n")
    out.append("    _ => raise self.not_const(op.visit_name())\n  }\n}\n")
    return "".join(out)


def gen_todo(ops):
    implemented = set()
    for path in glob.glob(os.path.join(OUT, "*.mbt")):
        if path.endswith("_gen.mbt"):
            continue
        for m in re.finditer(r"fn OperatorValidatorTemp::(visit_\w+)\(", open(path).read()):
            implemented.add(m.group(1))
    out = [HEADER]
    out.append(
        "// Stubs for the `OperatorValidatorTemp::visit_*` methods that are not\n// ported. Define one in a handwritten file and rerun the generator to drop\n// its stub.\n\n"
    )
    for proposal, name, fields, visit in ops:
        if visit in implemented:
            continue
        ps = "".join(f", _{f} : {t}" for f, t in fields)
        out.append("///|\n")
        out.append(
            f"fn OperatorValidatorTemp::{visit}(\n  self : OperatorValidatorTemp{ps},\n) -> Unit raise BinaryReaderError {{\n"
        )
        out.append(f"  raise self.not_ported(\"{visit}\")\n}}\n\n")
    return "".join(out)


def main():
    crate = find_crate()
    ops = parse_ops(os.path.join(crate, "src", "lib.rs"))
    assert len(ops) == len({o[3] for o in ops}), "duplicate visit names"
    files = {
        "readers_core_operators_gen.mbt": gen_operator(ops),
        "validator_operators_gen.mbt": gen_validator(ops),
        "validator_core_gen.mbt": gen_const(ops),
        "validator_operators_todo_gen.mbt": gen_todo(ops),
    }
    for name, text in files.items():
        with open(os.path.join(OUT, name), "w") as f:
            f.write(text)
    print(f"{len(ops)} operators")


if __name__ == "__main__":
    main()
