#!/usr/bin/env python3
"""Generate library/font_exceptions_gen.mbt from upstream
`typst-library/src/text/font/exceptions.rs` (the PostScript-name keyed
override table)."""
import re

SRC = '.repos/typst/crates/typst-library/src/text/font/exceptions.rs'
OUT = 'library/font_exceptions_gen.mbt'

src = open(SRC).read()
body = src[src.index('phf::phf_map! {'):]
rows = []
for line in body.splitlines():
    m = re.match(r'\s*"([^"]+)"\s*=>\s*E((?:\.\w+\([^)]*\))*),\s*$', line)
    if not m:
        continue
    name, calls = m.group(1), m.group(2)
    family = style = weight = stretch = 'None'
    for call, arg in re.findall(r'\.(\w+)\(([^)]*)\)', calls):
        if call == 'family':
            family = 'Some(%s)' % arg
        elif call == 'style':
            style = 'Some(%s)' % arg.replace('FontStyle::', '')
        elif call == 'weight':
            weight = 'Some(FontWeight(%s))' % arg
        elif call == 'stretch':
            stretch = 'Some(FontStretch(%s))' % arg
        else:
            raise Exception(call)
    rows.append((name, family, style, weight, stretch))

out = [
    '// Generated by scripts/gen_font_exceptions.py from upstream',
    '// `typst-library/src/text/font/exceptions.rs`. Do not edit.',
    '',
    '///|',
    'let exception_map : Map[String, Exception] = {',
]
for name, family, style, weight, stretch in rows:
    out.append('  "%s": { family: %s, style: %s, weight: %s, stretch: %s },'
               % (name, family, style, weight, stretch))
out.append('}')
open(OUT, 'w').write('\n'.join(out) + '\n')
print(len(rows), 'exceptions')
