#!/usr/bin/env python3
"""Generates `cli/help_gen.mbt`: the help texts of the upstream typst CLI.

The texts are captured from an upstream `typst` binary built from the pinned
revision (`cargo build --release -p typst-cli` in `.repos/typst`), with
`-h` (short) and `--help` (long) for the main command and every subcommand,
so that `typst.mbt`'s CLI prints the same help as upstream (clap renders
them with a maximum width of 80 columns when not attached to a terminal).

Usage: python3 scripts/gen_cli_help.py <path to upstream typst binary>
"""

import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "cli", "help_gen.mbt")

COMMANDS = ["", "compile", "watch", "init", "query", "eval", "fonts", "update", "completions", "info"]


def capture(binary, args):
    env = dict(os.environ)
    env.pop("COLUMNS", None)
    out = subprocess.run([binary, *args], capture_output=True, text=True, env=env, stdin=subprocess.DEVNULL)
    assert out.returncode == 0, (args, out.stderr)
    text = out.stdout
    name = os.path.basename(binary)
    if name != "typst":
        text = text.replace(f"Usage: {name}", "Usage: typst")
    return text


def literal(text):
    lines = text.split("\n")
    # Multi-line strings end without a newline; the trailing newline of the
    # help is added back by the caller.
    assert lines[-1] == ""
    out = []
    for line in lines[:-1]:
        out.append(f"  #|{line}\n")
    return "".join(out)


def main():
    binary = sys.argv[1]
    parts = [
        "// Generated by scripts/gen_cli_help.py from the help texts of the upstream\n",
        "// typst CLI at the pinned revision. Do not edit.\n\n",
    ]
    entries = []
    for i, command in enumerate(COMMANDS):
        args = [command] if command else []
        for kind, flag in (("short", "-h"), ("long", "--help")):
            text = capture(binary, [*args, flag])
            ident = f"help_{command or 'main'}_{kind}"
            parts.append(f"///|\nlet {ident} : String =\n{literal(text)}\n")
            entries.append((command, kind, ident))
    parts.append("///|\n/// The help texts: (command, long?, text without the final newline).\n")
    parts.append("let help_texts : Array[(String, Bool, String)] = [\n")
    for command, kind, ident in entries:
        parts.append(f'  ("{command}", {"true" if kind == "long" else "false"}, {ident}),\n')
    parts.append("]\n")
    with open(OUT, "w") as f:
        f.write("".join(parts))


if __name__ == "__main__":
    main()
