#!/usr/bin/env python3
"""Generate the data tables of the shaper (`shape/`) from the rustybuzz
sources they are ported from (rustybuzz's own generated tables).

Usage: gen_shape_tables.py [rustybuzz checkout, default .repos/rustybuzz]

Writes `shape/*_gen.mbt`. Never edit those by hand.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RB = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '.repos', 'rustybuzz')
HB = os.path.join(RB, 'src', 'hb')
OUT = os.path.join(ROOT, 'shape')

HEADER = '// Generated by scripts/gen_shape_tables.py from rustybuzz `src/hb/%s`.\n// Do not edit.\n\n'


def read(name):
    return open(os.path.join(HB, name), encoding='utf-8').read()


def char_lit(s):
    """Value of a Rust char literal body like `\\u{00C0}` or `a`."""
    m = re.fullmatch(r"\\u\{([0-9A-Fa-f]+)\}", s)
    if m:
        return int(m.group(1), 16)
    assert len(s) == 1, s
    return ord(s)


def emit_ints(name, doc, values, per_line=8, typ='FixedArray[Int]'):
    out = ['///|\n/// %s\nlet %s : %s = [\n' % (doc, name, typ)]
    for i in range(0, len(values), per_line):
        out.append('  ' + ' '.join('%s,' % v for v in values[i:i + per_line]) + '\n')
    out.append(']\n\n')
    return ''.join(out)


def body_of(src, start_marker):
    i = src.index(start_marker)
    i = src.index('[', src.index('=', i)) + 1
    depth = 1
    j = i
    while depth:
        c = src[j]
        if c == '[':
            depth += 1
        elif c == ']':
            depth -= 1
        j += 1
    return src[i:j - 1]


def gen_unicode_norm():
    src = read('unicode_norm.rs')
    dec = body_of(src, 'pub const DECOMPOSITION_TABLE')
    rows = re.findall(r"\('((?:\\u\{[0-9A-Fa-f]+\})|.)', '((?:\\u\{[0-9A-Fa-f]+\})|.)', (None|Some\('((?:\\u\{[0-9A-Fa-f]+\})|.)'\))\)", dec)
    flat = []
    for a, b, opt, c in rows:
        flat += ['0x%X' % char_lit(a), '0x%X' % char_lit(b), '0x%X' % (char_lit(c) if opt != 'None' else 0)]
    assert len(rows) == dec.count('\n    ('), 'decomposition rows'
    comp = body_of(src, 'pub const COMPOSITION_TABLE')
    crow = re.findall(r"\((\d+), '((?:\\u\{[0-9A-Fa-f]+\})|.)'\)", comp)
    assert len(crow) == comp.count('\n    ('), 'composition rows'
    cflat = []
    for needle, c in crow:
        n = int(needle)
        cflat += ['0x%X' % (n >> 32), '0x%X' % (n & 0xFFFFFFFF), '0x%X' % char_lit(c)]
    out = HEADER % 'unicode_norm.rs'
    out += emit_ints('decomposition_table', 'Canonical decompositions `[ab, a, b or 0]`, sorted by `ab`.', flat, 9)
    out += emit_ints('composition_table', 'Canonical compositions `[a, b, ab]`, sorted by `(a, b)`.', cflat, 9)
    open(os.path.join(OUT, 'unicode_norm_gen.mbt'), 'w').write(out)


def gen_emoji():
    src = read('unicode.rs')
    i = src.index('fn is_emoji_extended_pictographic')
    j = src.index('_ => false', i)
    ranges = []
    for m in re.finditer(r'0x([0-9A-F]+)(?:\.\.=0x([0-9A-F]+))? => true', src[i:j]):
        lo = int(m.group(1), 16)
        hi = int(m.group(2), 16) if m.group(2) else lo
        ranges += ['0x%X' % lo, '0x%X' % hi]
    out = HEADER % 'unicode.rs (is_emoji_extended_pictographic)'
    out += emit_ints('emoji_extended_pictographic_table', 'Extended_Pictographic ranges `[lo, hi]` (gen-unicode-is-emoji-ext-pict.py).', ranges, 8)
    open(os.path.join(OUT, 'unicode_emoji_gen.mbt'), 'w').write(out)


# --- Ragel state machines (`ot_shaper_*_machine.rs`) -------------------------


def rust_static_arrays(src):
    """All `static NAME: [T; N] = [...];` arrays of a Ragel-generated module, in
    source order, as `(name, values)`."""
    out = []
    for m in re.finditer(r'static (\w+): \[(\w+); (\d+)\] = \[([^\]]*)\];', src):
        name, _ty, n, body = m.groups()
        values = [int(v) for v in re.findall(r'-?\d+', body)]
        assert len(values) == int(n), name
        out.append((name, values))
    return out


def rust_static_scalars(src):
    return re.findall(r'static (\w+): i32 = (-?\d+);', src)


def gen_ragel_machine(module, out_name):
    """Writes the data tables of a Ragel machine; the driver is ported by hand.
    Leading underscores of the Ragel names are dropped."""
    src = read(module)
    out = HEADER % module
    for name, values in rust_static_arrays(src):
        out += emit_ints(name.lstrip('_'), 'Ragel table `%s`.' % name, values, 16)
    for name, value in rust_static_scalars(src):
        out += '///|\nconst %s : Int = %s\n\n' % (name.upper(), value)
    open(os.path.join(OUT, out_name), 'w').write(out)


# --- USE table (`ot_shaper_use_table.rs`) ------------------------------------


def use_categories():
    """`category::*` constants of `ot_shaper_use.rs` (name -> value)."""
    src = read('ot_shaper_use.rs')
    cats = {}
    for m in re.finditer(r'^\s*pub const (\w+): u8 = (\d+);', src, re.M):
        cats[m.group(1)] = int(m.group(2))
    return cats


def gen_use_table():
    src = read('ot_shaper_use_table.rs')
    cats = use_categories()
    out = HEADER % 'ot_shaper_use_table.rs'
    for name in ('hb_use_u8', 'hb_use_u16'):
        m = re.search(r'const %s: \[\w+; (\d+)\] =\s*\[([^\]]*)\];' % name, src)
        values = []
        for tok in re.findall(r'\w+', m.group(2)):
            values.append(int(tok) if tok.isdigit() else cats[tok])
        assert len(values) == int(m.group(1)), name
        out += emit_ints(name[3:], '`%s` (packTab).' % name, values, 16)
    open(os.path.join(OUT, 'ot_shaper_use_table_gen.mbt'), 'w').write(out)


# --- tag_table.rs (HarfBuzz gen-tag-table.py output) -------------------------

def tag_lit(b):
    """`@otf.Tag` literal of a 4-byte tag string."""
    assert len(b) == 4, b
    return '@otf.Tag::from_bytes(b"%s")' % b


def gen_tag_table():
    """`OPEN_TYPE_LANGUAGES` and the generated code of
    `tags_from_complex_language` (translated line by line; every line must
    match one of the known shapes). The helpers `subtag_matches`,
    `lang_matches` and `strncmp` are ported by hand in `shape/tag_table.mbt`.
    The output is not `moon fmt`-normalized (run `moon fmt` afterwards)."""
    src = read('tag_table.rs')
    out = HEADER % 'tag_table.rs'
    out = out.replace('.\n// Do not edit.', "\n// (itself generated by HarfBuzz's gen-tag-table.py). Do not edit.")

    # OPEN_TYPE_LANGUAGES
    body = body_of(src, 'pub const OPEN_TYPE_LANGUAGES')
    rows = []
    n = 0
    for line in body.split('\n'):
        if not line.strip():
            continue
        m = re.fullmatch(r'(    |//  )LangTag \{ language: "([a-z0-9]+)", \ttag: (?:Tag::from_bytes\(b"(.{4})"\) |Tag\(0\)\t            )\}, // (.*)', line)
        assert m, line
        lead, lang, tag, comment = m.groups()
        val = '0x%08X' % int.from_bytes(tag.encode('latin1'), 'big') if tag else '0'
        entry = '{ language: "%s", tag: @otf.Tag(%s) }, // %s %s' % (
            lang, val, ("'%s'" % tag) if tag else 'null', comment)
        if lead == '//  ':
            rows.append('  // ' + entry)
        else:
            rows.append('  ' + entry)
            n += 1
    assert n > 1400, n
    out += '///|\npriv struct LangTag {\n  language : String\n  tag : @otf.Tag\n}\n\n'
    out += '///|\n/// `OPEN_TYPE_LANGUAGES`, sorted by `language`.\n'
    out += 'let open_type_languages : FixedArray[LangTag] = [\n'
    out += '\n'.join(rows) + '\n]\n\n'

    # tags_from_complex_language: translate the generated Rust code line by line.
    i = src.index('/// Converts a multi-subtag BCP 47 language tag to language tags.')
    lines = src[i:].rstrip('\n').split('\n')
    TAG = r'Tag::from_bytes\(b"(.{4})"\)'
    STR = r'"([^"]*)"'
    rules = [
        (r'pub fn tags_from_complex_language\(language: &str, tags: &mut smallvec::SmallVec<\[Tag; 3\]>\) -> bool \{',
         lambda m, ind: 'fn tags_from_complex_language(\n  language : StringView,\n  tags : Array[@otf.Tag],\n) -> Bool {'),
        (r'if subtag_matches\(language, %s\) \{' % STR,
         lambda m, ind: 'if subtag_matches(language, "%s") {' % m.group(1)),
        (r'if lang_matches\(&language\[1\.\.\], %s\) \{' % STR,
         lambda m, ind: 'if lang_matches(language[1:], "%s") {' % m.group(1)),
        (r'if &language\[1\.\.\] == %s \{' % STR,
         lambda m, ind: 'if language[1:] == "%s" {' % m.group(1)),
        (r'if strncmp\(&language\[1\.\.\], %s, (\d+)\) && subtag_matches\(language, %s\) \{' % (STR, STR),
         lambda m, ind: 'if strncmp(language[1:], "%s", %s) && subtag_matches(language, "%s") {' % (
             m.group(1), m.group(2), m.group(3))),
        (r'tags\.push\(%s\);' % TAG, lambda m, ind: 'tags.push(%s)' % tag_lit(m.group(1))),
        (r'let possible_tags = &\[', lambda m, ind: 'let possible_tags = ['),
        (r'%s,' % TAG, lambda m, ind: tag_lit(m.group(1)) + ','),
        (r'\];', lambda m, ind: ']'),
        (r'tags\.extend_from_slice\(possible_tags\);', lambda m, ind: 'tags.append(possible_tags)'),
        (r'return true;', lambda m, ind: 'return true'),
        (r'match language\.as_bytes\(\)\[0\] \{', lambda m, ind: 'match language[0].to_int() {'),
        (r"b'([a-z])' => \{", lambda m, ind: "'%s' => {" % m.group(1)),
        (r'_ => \{\}', lambda m, ind: '_ => ()'),
        (r'\}', lambda m, ind: '}'),
        (r'false', lambda m, ind: 'false'),
        (r'/// (.*)', lambda m, ind: '///|\n/// ' + m.group(1)),
    ]
    res = []
    for line in lines:
        stripped = line.lstrip(' ')
        ind = ' ' * ((len(line) - len(stripped)) // 2)
        if stripped.startswith('//') and not stripped.startswith('///'):
            res.append(ind + stripped)
            continue
        m = re.fullmatch(r'(.*?)( // .*)?', stripped)
        code, comment = m.group(1), m.group(2) or ''
        for pat, f in rules:
            mm = re.fullmatch(pat, code)
            if mm:
                res.append(ind + f(mm, ind) + comment)
                break
        else:
            raise AssertionError('untranslated line: %r' % line)
    out += '\n'.join(res) + '\n'
    open(os.path.join(OUT, 'tag_table_gen.mbt'), 'w').write(out)

# ---------------------------------------------------------------------------
# ot_shaper_arabic_table.rs: the Arabic joining-type table and its lookup.


def gen_arabic_table():
    src = read('ot_shaper_arabic_table.rs')
    # Joining-type values (`hb_arabic_joining_type_t` discriminants).
    m = re.search(r'pub enum hb_arabic_joining_type_t \{(.*?)\}', read('ot_shaper_arabic.rs'), re.S)
    values = {}
    for name, v in re.findall(r'^\s*(\w+) = (\d+),', m.group(1), re.M):
        values[name] = int(v)
    alias = {'A': 'GroupAlaph', 'DR': 'GroupDalathRish'}
    for k in ('D', 'L', 'R', 'T', 'U', 'X'):
        alias[k] = k
    body = body_of(src, 'pub const JOINING_TABLE')
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)
    table = [values[alias[t]] for t in re.findall(r'[A-Z]+', body)]
    offsets = {}
    for name, v in re.findall(r'const (JOINING_OFFSET_0X[0-9A-F]+): usize = (\d+);', src):
        offsets[name] = int(v)
    fn = src[src.index('pub fn joining_type'):]
    arms = []
    for block in re.finditer(r'(0x[0-9A-F]+) => \{(.*?)\n        \}', fn, re.S):
        ranges = re.findall(
            r'\((0x[0-9A-F]+)\.\.=(0x[0-9A-F]+)\)\.contains\(&u\) \{\s*'
            r'return JOINING_TABLE\[u as usize - (0x[0-9A-F]+) \+ (JOINING_OFFSET_0X[0-9A-F]+)\]',
            block.group(2))
        assert ranges, block.group(0)
        arms.append((block.group(1), ranges))
    last = arms[-1][1][-1]
    assert len(table) == offsets[last[3]] + int(last[1], 16) - int(last[0], 16) + 1, len(table)
    out = HEADER % 'ot_shaper_arabic_table.rs'
    out += emit_ints('joining_table',
                     'Joining types (`hb_arabic_joining_type_t` values) of the covered ranges.',
                     table, 32)
    for name in sorted(offsets, key=lambda n: offsets[n]):
        out += '///|\nconst %s : Int = %d\n\n' % (name, offsets[name])
    out += '///|\nfn joining_type(u : Int) -> Int {\n  match u >> 12 {\n'
    for key, ranges in arms:
        out += '    %s => {\n' % key
        for lo, hi, base, off in ranges:
            assert lo == base
            out += ('      if u >= %s && u <= %s {\n'
                    '        return joining_table[u - %s + %s]\n      }\n') % (lo, hi, base, off)
        out += '    }\n'
    out += '    _ => ()\n  }\n  JOINING_TYPE_X\n}\n'
    open(os.path.join(OUT, 'ot_shaper_arabic_table_gen.mbt'), 'w').write(out)


if __name__ == '__main__':
    gen_unicode_norm()
    gen_emoji()
    gen_ragel_machine('ot_shaper_use_machine.rs', 'ot_shaper_use_machine_gen.mbt')
    gen_use_table()
    gen_tag_table()
    gen_arabic_table()
