#!/usr/bin/env python3
"""Converts the constant tables of image-webp's VP8 decoder (`src/vp8.rs`) into
`codecs/webp_vp8_tables_gen.mbt` (flattened, row-major).

Usage: python3 scripts/gen_webp_tables.py [path to image-webp-0.2.4/src/vp8.rs]
"""
import glob
import os
import re
import sys

TABLES = [
    "KEYFRAME_BPRED_MODE_PROBS",
    "COEFF_UPDATE_PROBS",
    "COEFF_PROBS",
    "DC_QUANT",
    "AC_QUANT",
    "PROB_DCT_CAT",
]


def main():
    if len(sys.argv) > 1:
        src = sys.argv[1]
    else:
        src = sorted(glob.glob(os.path.expanduser(
            "~/.cargo/registry/src/*/image-webp-0.2.4/src/vp8.rs")))[0]
    text = open(src).read()
    out = [
        "// Generated by scripts/gen_webp_tables.py from image-webp 0.2.4 (src/vp8.rs).",
        "// Do not edit.",
    ]
    for name in TABLES:
        m = re.search(r"const " + name + r"\s*:[^=]*=\s*\[", text)
        if not m:
            raise SystemExit("table not found: " + name)
        i = m.end() - 1
        depth = 0
        j = i
        while True:
            c = text[j]
            if c == "[":
                depth += 1
            elif c == "]":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        body = text[i : j + 1]
        body = re.sub(r"//[^\n]*", "", body)
        nums = [int(x) for x in re.findall(r"-?\d+", body)]
        lines = []
        row = []
        for n in nums:
            row.append(str(n))
            if len(row) == 16:
                lines.append("  " + ", ".join(row) + ",")
                row = []
        if row:
            lines.append("  " + ", ".join(row) + ",")
        out.append("")
        out.append("///|")
        out.append("/// `%s` (%d entries)." % (name, len(nums)))
        mbt_name = name.lower() + ("_table" if name.endswith("_QUANT") else "")
        out.append("let %s : ReadOnlyArray[Int] = [" % mbt_name)
        out.extend(lines)
        out.append("]")
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
    open(os.path.join(root, "codecs", "webp_vp8_tables_gen.mbt"), "w").write(
        "\n".join(out) + "\n")


main()
