#!/usr/bin/env python3
"""Generate `library/cmyk_icc_gen.mbt` from typst-assets' `CMYK-to-XYZ.icc`.

Upstream converts CMYK to sRGB with `moxcms` using this profile (see
`typst-library/src/visualize/color.rs`). The profile's `A2B0` tag is an
`mft2` (lut16) table: input curves, a 4D CLUT and output curves. This script
extracts the tables; `library/cmyk_icc.mbt` evaluates them like `moxcms`.

Usage: python3 scripts/gen_cmyk_icc.py [path/to/CMYK-to-XYZ.icc]
"""

import glob
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def find_profile():
    pattern = os.path.expanduser(
        "~/.cargo/git/checkouts/typst-assets-*/*/files/icc/CMYK-to-XYZ.icc"
    )
    found = sorted(glob.glob(pattern))
    if not found:
        sys.exit("CMYK-to-XYZ.icc not found; pass its path")
    return found[-1]


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else find_profile()
    data = open(path, "rb").read()
    count = struct.unpack(">I", data[128:132])[0]
    tags = {}
    for i in range(count):
        sig, off, size = struct.unpack(">4sII", data[132 + 12 * i : 144 + 12 * i])
        tags[sig] = data[off : off + size]
    a2b0 = tags[b"A2B0"]
    assert a2b0[:4] == b"mft2"
    ins, outs, grid = a2b0[8], a2b0[9], a2b0[10]
    n_in, n_out = struct.unpack(">HH", a2b0[48:52])
    assert (ins, outs) == (4, 3)
    off = 52
    in_tab = struct.unpack(f">{ins * n_in}H", a2b0[off : off + 2 * ins * n_in])
    off += 2 * ins * n_in
    n_clut = grid**ins * outs
    clut = struct.unpack(f">{n_clut}H", a2b0[off : off + 2 * n_clut])
    off += 2 * n_clut
    out_tab = struct.unpack(f">{outs * n_out}H", a2b0[off : off + 2 * outs * n_out])

    def arr(name, values):
        lines = []
        for i in range(0, len(values), 12):
            lines.append("  " + ", ".join(str(v) for v in values[i : i + 12]) + ",")
        return f"///|\nlet {name} : ReadOnlyArray[Int] = [\n" + "\n".join(lines) + "\n]\n"

    out = [
        "// Generated by scripts/gen_cmyk_icc.py from typst-assets' CMYK-to-XYZ.icc.",
        "// Do not edit.\n",
        f"///|\nlet cmyk_icc_grid_points : Int = {grid}\n",
        f"///|\nlet cmyk_icc_input_entries : Int = {n_in}\n",
        f"///|\nlet cmyk_icc_output_entries : Int = {n_out}\n",
        arr("cmyk_icc_input_tables", in_tab),
        arr("cmyk_icc_clut", clut),
        arr("cmyk_icc_output_tables", out_tab),
    ]
    with open(os.path.join(ROOT, "library", "cmyk_icc_gen.mbt"), "w") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main()
