#!/usr/bin/env python3
"""Generate hayro/jbig2/huffman_tables_gen.mbt from hayro-jbig2's
`src/huffman_tables_generated.rs` (the standard Huffman tables B.1-B.15 as
inline node arrays).

Usage: python3 scripts/gen_jbig2_huffman_tables.py [path/to/hayro-jbig2]
(default: target/hayro/hayro-jbig2, the development checkout symlink).
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    crate = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "target/hayro/hayro-jbig2")
    src = open(os.path.join(crate, "src/huffman_tables_generated.rs")).read()
    out = [
        "// Generated by scripts/gen_jbig2_huffman_tables.py from",
        "// `hayro-jbig2/src/huffman_tables_generated.rs`. Do not edit.",
        "",
    ]
    table_re = re.compile(
        r"/// (Standard Huffman table \w \(Table B\.\d+\)\.)\n#\[rustfmt::skip\]\n"
        r"const (TABLE_\w): \[N; INLINE_TABLE_SIZE\] = \[\n(.*?)\n\];",
        re.S,
    )
    inter_re = re.compile(r"N::Intermediate \{ zero: (Some\(nz\((\d+)\)\)|None), one: (Some\(nz\((\d+)\)\)|None) \},")
    leaf_re = re.compile(
        r"N::Leaf\(L \{ range_low: (-?\d+), range_length: (\d+), is_lower: (true|false), "
        r"is_out_of_band: (true|false) \}\),"
    )
    count = 0
    for doc, name, body in table_re.findall(src):
        nodes = []
        for line in body.split("\n"):
            line = line.strip()
            if line == "N::Empty,":
                nodes.append("Empty")
                continue
            m = inter_re.fullmatch(line)
            if m:
                zero = m.group(2) or "0"
                one = m.group(4) or "0"
                nodes.append(f"Intermediate(zero={zero}, one={one})")
                continue
            m = leaf_re.fullmatch(line)
            if m:
                nodes.append(
                    f"HuffmanNode::new_leaf({m.group(1)}, {m.group(2)}, {m.group(3)}, {m.group(4)})"
                )
                continue
            raise SystemExit(f"unexpected line in {name}: {line!r}")
        assert len(nodes) == 43, (name, len(nodes))
        out.append("///|")
        out.append(f"/// {doc}")
        out.append(f"let {name.lower()}_nodes : FixedArray[HuffmanNode] = [")
        for n in nodes:
            out.append(f"  {n},")
        out.append("]")
        out.append("")
        count += 1
    assert count == 15, count
    path = os.path.join(ROOT, "hayro/jbig2/huffman_tables_gen.mbt")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
