#!/usr/bin/env python3
"""Generate typed element views (`library/elem_views_gen.mbt`).

Upstream code accesses element fields through typed, macro-generated APIs
(`elem.body`, `elem.level.get(styles)`, `HeadingElem::level.set(..)`).
Our elements store fields as `Value`s (see docs/p2-architecture.md), so this
generates typed views over them, keeping ports of realize/html/layout code
mechanical (see docs/p3-plan.md, section 2):

    HeadingElem::of(content) -> HeadingElem?     // `to_packed::<HeadingElem>()`
    HeadingElem::pack(self) -> Content
    HeadingElem::new(required...) -> HeadingElem
    elem.body() -> Content                       // required field
    elem.level(styles) -> Smart[..]              // settable: `level.get(styles)`
    HeadingElem::level_in(styles) -> ..          // `styles.get(HeadingElem::level)`
    elem.level_local() -> ..?                    // the element's own value
    elem.numbering() -> ..?                      // synthesized field
    elem.with_level(v) -> HeadingElem            // set the element's own value
    HeadingElem::set_level(v) -> Style           // `HeadingElem::level.set(v)`

Field values are stored already cast, so the getters cast back infallibly
(a failure means a missing default port and aborts with the field name).
Views of handwritten `struct X(Content)` wrappers reuse them, and
handwritten methods with the same name win.
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from typemap import mbt_type  # noqa: E402
from elemgen import elem_var, snake, SKIP  # noqa: E402

import json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIB = os.path.join(ROOT, "library")

# MoonBit keywords and reserved words that can't be method names.
RESERVED = {
    "as", "else", "extern", "fn", "fnalias", "if", "let", "const", "match",
    "using", "mut", "type", "typealias", "struct", "enum", "trait",
    "traitalias", "derive", "while", "break", "continue", "import", "return",
    "throw", "raise", "try", "catch", "pub", "priv", "readonly", "true",
    "false", "_", "test", "loop", "for", "in", "impl", "with", "guard",
    "async", "is", "suberror", "and", "letrec", "enumview", "noraise",
    "defer", "init", "main", "method", "constructor", "virtual", "where",
    "lazy", "sealed", "module", "move", "ref", "static", "super", "unsafe",
    "use", "yield", "macro", "extends", "extend", "include", "abstract",
    "proc", "do", "final", "export", "open", "of", "pack", "new",
}


def view_name(e):
    ident = e["ident"]
    var = elem_var(ident, e["file"])
    if var.startswith("math_"):
        return "Math" + ident
    if var.startswith("pdf_"):
        return "Pdf" + ident
    return ident


def handwritten():
    """Content-wrapper structs and `Type::method` names defined by hand."""
    structs, methods, types = set(), set(), set()
    for fn in os.listdir(LIB):
        if not fn.endswith(".mbt") or fn.endswith("_gen.mbt"):
            continue
        src = open(os.path.join(LIB, fn)).read()
        for m in re.finditer(r"^(?:pub(?:\(all\))? )?struct ([A-Z]\w*)\(Content\)", src, re.M):
            structs.add(m.group(1))
        for m in re.finditer(
            r"^(?:pub(?:\(all\))? )?(?:struct|enum|type|suberror|trait) ([A-Z]\w*)", src, re.M
        ):
            types.add(m.group(1))
        for m in re.finditer(r"^(?:pub )?fn (?:\[[^\]]*\] )?([A-Z]\w*)::([a-z_]\w*)", src, re.M):
            methods.add(f"{m.group(1)}::{m.group(2)}")
    return structs, methods, types


def method_name(name):
    return name + "_" if name in RESERVED else name


def main():
    manifest = json.load(open(os.path.join(ROOT, "gen", "manifest.json")))
    structs, methods, types = handwritten()
    out = ["// Generated by scripts/viewgen.py from gen/manifest.json. Do not edit.\n"]
    out.append(
        "///|\n/// Cast a stored field value back to its field type.\nfn[T : FromValue] view_cast(v : Value, what : String) -> T {\n"
        "  T::from_value(v) catch {\n    _ => abort(\"field `\\{what}` holds an unexpected value: \\{v.repr()}\")\n  }\n}\n"
    )
    count = 0
    for e in manifest["elems"]:
        if e["ident"] in SKIP:
            continue
        name = view_name(e)
        if name in types and name not in structs:
            print(f"skipping view {name}: name taken by a non-view type", file=sys.stderr)
            continue
        var = elem_var(e["ident"], e["file"])
        count += 1
        defs = []

        def emit(method, code):
            if f"{name}::{method}" in methods:
                return
            defs.append(code)

        if name not in structs:
            defs.append(
                f"///|\n/// Typed view of `{e['name']}` content (upstream `Packed<{e['ident']}>`).\n"
                f"pub struct {name}(Content)\n"
            )
        emit("of", f"///|\n/// View content as `{e['name']}` if it is one.\npub fn {name}::of(c : Content) -> {name}? {{\n"
                   f"  if c.elem() == {var}() {{\n    Some({name}(c))\n  }} else {{\n    None\n  }}\n}}\n")
        emit("pack", f"///|\npub fn {name}::pack(self : {name}) -> Content {{\n  self.0\n}}\n")
        required = []
        for i, f in enumerate(e["fields"]):
            if f["external"]:
                continue
            ty = mbt_type(f["ty"])
            field_const = f"{var}_{snake(f['ident'])}"
            m = method_name(snake(f["ident"]))
            what = f"{e['name']}.{f['name']}"
            if f["required"] or f["variadic"]:
                required.append((m, ty, field_const))
                emit(m, f"///|\npub fn {name}::{m}(self : {name}) -> {ty} {{\n"
                        f"  view_cast(self.0.field_raw({field_const}).unwrap(), {json.dumps(what)})\n}}\n")
                emit(f"with_{snake(f['ident'])}",
                     f"///|\npub fn {name}::with_{snake(f['ident'])}(self : {name}, v : {ty}) -> {name} {{\n"
                     f"  {name}(self.0.with_field({field_const}, IntoValue::into_value(v)))\n}}\n")
            elif f["synthesized"]:
                emit(m, f"///|\npub fn {name}::{m}(self : {name}) -> {ty}? {{\n"
                        f"  match self.0.field_raw({field_const}) {{\n    Some(v) => Some(view_cast(v, {json.dumps(what)}))\n    None => None\n  }}\n}}\n")
                emit(f"with_{snake(f['ident'])}",
                     f"///|\npub fn {name}::with_{snake(f['ident'])}(self : {name}, v : {ty}) -> {name} {{\n"
                     f"  {name}(self.0.with_field({field_const}, IntoValue::into_value(v)))\n}}\n")
            else:
                ghost = f["ghost"]
                if not ghost:
                    emit(m, f"///|\npub fn {name}::{m}(self : {name}, styles : StyleChain) -> {ty} {{\n"
                            f"  let e = {var}()\n"
                            f"  view_cast(styles.get_value_with_local(e, e.fields()[{field_const}], self.0.field_raw({field_const})), {json.dumps(what)})\n}}\n")
                    emit(f"{snake(f['ident'])}_local",
                         f"///|\npub fn {name}::{snake(f['ident'])}_local(self : {name}) -> {ty}? {{\n"
                         f"  match self.0.field_raw({field_const}) {{\n    Some(v) => Some(view_cast(v, {json.dumps(what)}))\n    None => None\n  }}\n}}\n")
                    emit(f"with_{snake(f['ident'])}",
                         f"///|\npub fn {name}::with_{snake(f['ident'])}(self : {name}, v : {ty}) -> {name} {{\n"
                         f"  {name}(self.0.with_field({field_const}, IntoValue::into_value(v)))\n}}\n")
                emit(f"{snake(f['ident'])}_in",
                     f"///|\npub fn {name}::{snake(f['ident'])}_in(styles : StyleChain) -> {ty} {{\n"
                     f"  view_cast(styles.get_field({var}(), {field_const}), {json.dumps(what)})\n}}\n")
                emit(f"set_{snake(f['ident'])}",
                     f"///|\npub fn {name}::set_{snake(f['ident'])}(v : {ty}) -> Style {{\n"
                     f"  Property(Property::new({var}(), {field_const}, IntoValue::into_value(v)))\n}}\n")
        params = ", ".join(f"{m.rstrip('_')}_ : {ty}" for m, ty, _ in required)
        fields = ", ".join(f"({c}, IntoValue::into_value({m.rstrip('_')}_))" for m, _, c in required)
        emit("new", f"///|\npub fn {name}::new({params}) -> {name} {{\n  {name}(Content::new({var}(), [{fields}]))\n}}\n")
        out.extend(defs)
    with open(os.path.join(LIB, "elem_views_gen.mbt"), "w") as fh:
        fh.write("\n".join(out))
    print(f"{count} element views", file=sys.stderr)


if __name__ == "__main__":
    main()
