// physica 0.9.8: derivatives (`dv`, `pdv` with orders, mixed orders, styles), differentials
// (`dd`, `var`, `difference`), vectors and vector calculus, braces (`Set`, `Order`,
// `evaluated`, `expval`), bra-ket, special matrices (dmat, admat, imat, zmat, jmat, hmat,
// xmat, rotations, grammat, mdet), tensors, isotopes, Taylor terms, `hbar`, `signals`.
// Engine: math layout of attach/lr/mid/mat/frac built from code, `measure` inside context
// (large-style derivatives), numbered equations with references, inline vs. display.
#import "@preview/physica:0.9.8": *

#set page(width: 165mm, height: 190mm, margin: (x: 13mm, y: 14mm), numbering: "1")
#set text(size: 10pt)
#set par(justify: true)
#set heading(numbering: "1.")
#set math.equation(numbering: "(1)")

#align(center, text(14pt, weight: "bold")[Notes on a Spinning Top and a Particle in a Well])

= Kinematics

A point of the top has position $vb(r)(t)$ and velocity $vb(v) = dv(vb(r), t)$;
its acceleration is $vb(a) = dv(vb(r), t, 2)$. In components along the unit
vectors $vu(e)_1, vu(e)_2, vu(e)_3$ the arrow notation $va(omega)$ is used for the
angular velocity, so that
$ vb(v) = va(omega) cprod vb(r), quad vb(v) dprod va(omega) = 0, quad
  abs(vb(v))^2 = omega^2 r^2 - (va(omega) dprod vb(r))^2. $ <eq-v>
The derivative can be written in other styles: horizontal $dv(f, x, style: "horizontal")$,
skewed $dv(f, x, 2, style: "skewed")$, as an operator $dv(, t)$ acting on what follows, or
with a finite difference $dv(x, t, d: Delta)$. A large operator adapts to its argument:
$ dv(vec(x, y, z), t, style: "large") = vec(dot(x), dot(y), dot(z)),
  quad pdv(, x, y, style: "large") (x^2 y + sin(x y)). $

Rotations about the axes are generated by
$ R_z (phi) = rot3zmat(phi), quad R_x (theta) = rot3xmat(theta), \
  R(alpha + beta) = rot2mat(alpha + beta, delim: "["), $ <eq-rot>
and $R_y (psi) = rot3ymat(psi)$ completes the set. From @eq-rot the determinant is
$mdet(cos phi, -sin phi; sin phi, cos phi) = 1$.

= Fields

The potential $U(x, y, z)$ gives the force $vb(F) = -grad U$. For a field $vb(A)$,
$ div vb(A) = pdv(A_x, x) + pdv(A_y, y) + pdv(A_z, z), \
  curl (grad U) = vb(0), quad div (curl vb(A)) = 0, quad laplacian U = div (grad U). $ <eq-field>
Mixed partial derivatives add their orders automatically:
$ pdv(f, x, y), quad pdv(f, x, 2), quad pdv(f, x, y, 2), quad pdv(f, x, y, [1, 2]), \
  pdv(f, x, y, z, [2, n, k+1]), quad pdv(f, x, y, [m, n], total: N), quad
  pdv(u, x_i, x_j, [2, 3]), quad pdv(phi, t, d: delta). $ <eq-pdv>
Differentials come with thin spaces: $integral f dd(x)$, $integral.double g dd(x, y)$,
$integral.triple h dd(x, y, z, 3)$, $dd(x, y, [2, 3])$, $dd(x, y, prod: and)$,
$dd(V, compact: #true)$; a variation is $var(S) = 0$, a difference $difference(E)$.

The Jacobian of the map $(r, phi) |-> (x, y)$ and the Hessian of $U$ are
$ J = jmat(x, y; r, phi) = mat(cos phi, -r sin phi; sin phi, r cos phi), quad
  H = hmat(U; x, y, z, big: #true). $ <eq-jac>
Inline they are cramped: $jmat(f, g; u, v)$ and $hmat(f; x, y, delim: "[")$.

Other matrices that appear below:
$ dmat(I_1, I_2, I_3), quad dmat(1, 2, delim: "[", fill: 0), quad admat(a, b, c), quad
  imat(3), quad imat(2, fill: dot.c), quad zmat(2), \
  xmat(3, 3, #((i, j) => $g^(#(i - 1) #(j - 1))$)), quad grammat(vb(u), vb(v)), quad
  grammat(u, v, w, norm: #true, delim: "|"). $ <eq-mats>

#pagebreak(weak: true)

= The Well

The energy levels are the set $Set(E_n; n in NN)$, also written $Set(E_1, E_2, dots;)$
or $Set((n, E_n); n >= 1, E_n < V_0)$. With $hbar$ the reduced Planck constant,
$ i hbar pdv(, t) ket(psi) = hat(H) ket(psi), quad
  braket(psi) = 1, quad braket(phi, psi) = integral phi^* psi dd(x), \
  mel(m, hat(x), n) = sqrt(hbar / (2 m omega)) (sqrt(n) delta_(m, n-1) + sqrt(n+1) delta_(m, n+1)). $ <eq-qm>
Projectors are $ketbra(n)$ and transitions $ketbra(m, n)$; a bra alone is $bra(phi)$, a
tall one $bra(vec(1, 0))$. Expectation values: $expval(hat(p))$, $expval(hat(x)^2, psi)$,
$ expval(hat(H)) = evaluated(pdv(, beta) (-ln Z))_(beta = 1 slash k T) + Order(hbar^2),
  quad f(x) = order(x^2) quad (x -> 0). $ <eq-exp>
As @eq-qm shows, the matrix of $hat(x)$ is tridiagonal; its trace and rank are
$tr hat(x) = 0$ and $rank hat(x) = oo$, and $Re z$, $Im z$, $sgn x$, $Res_(z = 0) f$,
$diag(1, 2)$, $trace A$, $Trace A$ are available as operators.

Near the minimum $x_0$ the potential is expanded term by term:
$ U(x) approx taylorterm(U, x, x_0, 0) + taylorterm(U, x, x_0, 1) + taylorterm(U, x, x_0, 2) \
  + dots + taylorterm(U, x, x_0, n) + taylorterm(U, x, a + b, k - 1). $ <eq-taylor>

= Relativity and Nuclei

Index positions are kept apart: $tensor(T, +mu, -nu)$, $tensor(Gamma, +lambda, -mu, -nu)$,
$tensor(R, -a, -b, +c, -d)$, $tensor(epsilon, -i, -j, -k)$, with
$ tensor(R, +rho, -sigma, -mu, -nu) = partial_mu tensor(Gamma, +rho, -nu, -sigma)
  - partial_nu tensor(Gamma, +rho, -mu, -sigma)
  + tensor(Gamma, +rho, -mu, -lambda) tensor(Gamma, +lambda, -nu, -sigma)
  - tensor(Gamma, +rho, -nu, -lambda) tensor(Gamma, +lambda, -mu, -sigma). $ <eq-riemann>
A decay chain: $isotope(U, a: 238, z: 92) -> isotope("Th", a: 234, z: 90) + isotope("He", a: 4, z: 2)$,
then $isotope("Th", a: 234) -> isotope("Pa", a: 234) + e^- + macron(nu)_e$, and the neutral
$isotope(n, a: 1, z: 0)$.

The detector reads two pulse trains, the second one drawn in red:
#grid(
  columns: 2,
  column-gutter: 2em,
  signals("&u1uH&M'n|0M'&H'nH", step: 0.8em), signals("H'|L'|H|L", color: red),
)

#table(
  columns: (auto, 1fr, auto),
  align: (left, left, center),
  table.header[*Quantity*][*Expression*][*Equation*],
  [velocity], [$va(omega) cprod vb(r)$], [@eq-v],
  [divergence], [$div vb(A)$], [@eq-field],
  [Jacobian], [$jmat(x, y; r, phi)$], [@eq-jac],
  [energy], [$expval(hat(H))$], [@eq-exp],
  [curvature], [$tensor(R, +rho, -sigma, -mu, -nu)$], [@eq-riemann],
)

Equations @eq-pdv, @eq-mats and @eq-taylor collect the notation.
